[CmdletBinding()]
param(
    [string]$ProjectRoot = (Get-Location).Path,
    [switch]$IncludeTwinCATAds,
    [string]$TwinCATAdsSource,
    [string]$AgentVersion = '0.67.68',
    [switch]$RequirePython,
    [switch]$UseLatestPackageVersions,
    [switch]$UpdatePrerequisites
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$IsWindowsPlatform = if (Get-Variable -Name 'IsWindows' -ErrorAction SilentlyContinue) {
    [bool]$IsWindows
}
else {
    ($PSVersionTable.PSEdition -eq 'Desktop') -or ([Environment]::OSVersion.Platform -eq [PlatformID]::Win32NT)
}

$InstallerScriptPath = if ($MyInvocation.MyCommand.Path) { $MyInvocation.MyCommand.Path } else { $PSCommandPath }
$ResolvedProjectRoot = (Resolve-Path -LiteralPath $ProjectRoot -ErrorAction Stop).Path
$UserProfilePath = [Environment]::GetFolderPath('UserProfile')
$GlobalPiAgentDir = Join-Path $UserProfilePath '.pi\agent'
$GlobalPiAgentAuthPath = Join-Path $GlobalPiAgentDir 'auth.json'
$PiLensToolsDir = Join-Path $UserProfilePath '.pi-lens\tools'
$ProjectScriptsDir = Join-Path $ResolvedProjectRoot 'scripts'
$PiDir = Join-Path $ResolvedProjectRoot '.pi'
$SettingsPath = Join-Path $PiDir 'settings.json'
$ShimDir = Join-Path $PiDir 'bin'
$PythonShimPath = Join-Path $ShimDir 'python3.cmd'
$StartScriptPath = Join-Path $ProjectScriptsDir 'start-pi.ps1'
$SettingsBackupDir = Join-Path $PiDir 'backups'
$LogsDir = Join-Path $PiDir 'logs'
$InstallLogPath = Join-Path $LogsDir ("install-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.log')
$TranscriptStarted = $false
$ScriptExitCode = 0

$PackageNames = @(
    'mempalace-pi',
    'pi-lens',
    'pi-mcp-adapter',
    'pi-subagents',
    'pi-web-access'
)

function Write-Step {
    param([Parameter(Mandatory = $true)][string]$Message)
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

function Write-Info {
    param([Parameter(Mandatory = $true)][string]$Message)
    Write-Host "[info] $Message" -ForegroundColor DarkGray
}

function Write-ErrorLine {
    param([Parameter(Mandatory = $true)][string]$Message)
    Write-Host "[error] $Message" -ForegroundColor Red
}

function Refresh-ProcessPath {
    $machinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    $combined = @($machinePath, $userPath) -join ';'
    if (-not [string]::IsNullOrWhiteSpace($combined)) {
        $env:Path = $combined
    }
}

function Ensure-Directory {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

function Set-GeneratedAgentsSection {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$GeneratedContent
    )

    $beginMarker = '<!-- BEGIN PI-SETUP-AUTOGENERATED -->'
    $endMarker = '<!-- END PI-SETUP-AUTOGENERATED -->'
    $block = $beginMarker + "`r`n" + $GeneratedContent.Trim() + "`r`n" + $endMarker + "`r`n"

    $existing = ''
    if (Test-Path -LiteralPath $Path) {
        $existing = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    }

    if ($existing -match [regex]::Escape($beginMarker) + '[\s\S]*?' + [regex]::Escape($endMarker)) {
        $updated = [regex]::Replace($existing, [regex]::Escape($beginMarker) + '[\s\S]*?' + [regex]::Escape($endMarker), $block.TrimEnd())
        Set-Content -LiteralPath $Path -Value ($updated.TrimEnd() + "`r`n") -Encoding UTF8
        return
    }

    $prefix = @"
# AGENTS.md

This file contains instructions for coding agents working in this repository.

"@

    if ([string]::IsNullOrWhiteSpace($existing)) {
        Set-Content -LiteralPath $Path -Value ($prefix + $block) -Encoding UTF8
    }
    else {
        $separator = if ($existing.EndsWith("`n")) { "" } else { "`r`n" }
        Set-Content -LiteralPath $Path -Value ($existing + $separator + "`r`n" + $block) -Encoding UTF8
    }
}

function Get-AgentsMdContent {
    $twincatSection = if ($IncludeTwinCATAds -or -not [string]::IsNullOrWhiteSpace($TwinCATAdsSource)) { @"
- `pi-twincat-ads`: Use for TwinCAT ADS communication and related automation tasks when the project requires it.
"@ } else { "" }

    return @"
## Pi setup tools available in this workspace

Installed Pi packages:
- `pi-lens`: Prefer this for code understanding, LSP navigation, references, definitions, hover info, AST-aware search, and precise code changes.
- `mempalace-pi`: Treat this as a core part of the workflow. Use it actively for memory workflows, persistent project knowledge, reminders, decisions, follow-ups, and important discoveries that should survive the current session.
- `pi-subagents`: Use subagents when a task benefits from decomposition, parallel exploration, or specialized analysis.
- `pi-mcp-adapter`: Use MCP servers/tools when project tasks require external integrations or structured tool access.
- `pi-web-access`: Use web search/fetch only for external documentation or information not available in the repository.
$twincatSection
## Agent usage guidance

- Start with local repository context first: inspect files, settings, scripts, and code before using external tools.
- Use `mempalace-pi` as an active workflow component, not just as optional storage.
- When you learn something likely to matter later, store it in `mempalace-pi`.
- Before or during complex work, consider whether relevant prior knowledge from `mempalace-pi` may exist.
- Prefer `pi-lens`/LSP and AST-aware search over plain text search when navigating or modifying code.
- Use `pi-subagents` only when the task is complex enough to benefit from delegation.
- Use `pi-mcp-adapter` and `pi-web-access` deliberately, not by default.
- Keep edits minimal, precise, and consistent with the existing repository structure.
- When changing behavior, also update nearby documentation and scripts if needed.
- For Python-backed features such as `mempalace-pi` on Windows, prefer the provided start scripts and UTF-8 environment settings.

## Local project note

This `AGENTS.md` section was generated by `scripts/install-pi-stack.ps1`.
You may add project-specific instructions outside the autogenerated block.
"@
}

function Test-CommandExists {
    param([Parameter(Mandatory = $true)][string]$Name)
    return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Get-CommandPathSafe {
    param([Parameter(Mandatory = $true)][string]$Name)

    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }

    return $null
}

function Test-MapHasKey {
    param(
        [Parameter(Mandatory = $true)]$Map,
        [Parameter(Mandatory = $true)][string]$Key
    )

    if ($null -eq $Map) { return $false }
    if ($Map -is [System.Collections.IDictionary]) { return $Map.Contains($Key) }

    $property = $Map.PSObject.Properties[$Key]
    return $null -ne $property
}

function Invoke-External {
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [string[]]$Arguments = @(),
        [string]$WorkingDirectory
    )

    if ($WorkingDirectory) {
        Push-Location $WorkingDirectory
    }

    try {
        Write-Info ("Run: " + $FilePath + ' ' + ($Arguments -join ' '))
        & $FilePath @Arguments
        $exitCode = $LASTEXITCODE
        if ($exitCode -ne 0) {
            throw "Command failed ($exitCode): $FilePath $($Arguments -join ' ')"
        }
    }
    finally {
        if ($WorkingDirectory) {
            Pop-Location
        }
    }
}

function Invoke-WithRetry {
    param(
        [Parameter(Mandatory = $true)][scriptblock]$Action,
        [Parameter(Mandatory = $true)][string]$Description,
        [int]$MaxAttempts = 3,
        [int]$DelaySeconds = 4
    )

    $attempt = 0
    while ($attempt -lt $MaxAttempts) {
        $attempt++
        try {
            Write-Info "$Description (attempt $attempt/$MaxAttempts)"
            & $Action
            return
        }
        catch {
            if ($attempt -ge $MaxAttempts) {
                throw
            }
            Write-Warning "$Description failed: $($_.Exception.Message)"
            Write-Info "Waiting $DelaySeconds seconds before the next attempt ..."
            Start-Sleep -Seconds $DelaySeconds
        }
    }
}

function Get-PythonCommandSpec {
    param([Parameter(Mandatory = $true)][string]$PythonPath)

    $leaf = Split-Path -Leaf $PythonPath
    $baseArguments = @()
    if ($leaf -ieq 'py.exe' -or $leaf -ieq 'py') {
        $baseArguments += '-3'
    }

    return [ordered]@{
        FilePath      = $PythonPath
        BaseArguments = $baseArguments
    }
}

function Invoke-PythonCommand {
    param(
        [Parameter(Mandatory = $true)][string]$PythonPath,
        [Parameter(Mandatory = $true)][string[]]$Arguments,
        [string]$WorkingDirectory
    )

    $pythonSpec = Get-PythonCommandSpec -PythonPath $PythonPath
    $allArguments = @($pythonSpec['BaseArguments']) + @($Arguments)
    Invoke-External -FilePath $pythonSpec['FilePath'] -Arguments $allArguments -WorkingDirectory $WorkingDirectory
}

function Install-MemPalacePythonBackend {
    param([Parameter(Mandatory = $true)][string]$PythonPath)

    $env:PYTHONUTF8 = '1'
    $env:PYTHONIOENCODING = 'utf-8'

    Write-Step 'Installing MemPalace Python backend'
    Invoke-WithRetry -Description 'python -m pip install --upgrade mempalace' -Action {
        Invoke-PythonCommand -PythonPath $PythonPath -Arguments @('-m', 'pip', 'install', '--upgrade', 'mempalace')
    } -MaxAttempts 3 -DelaySeconds 5

    Write-Step 'Validating MemPalace Python backend'
    Invoke-PythonCommand -PythonPath $PythonPath -Arguments @('-c', 'import mempalace; import mempalace.mcp_server')
}

function Write-Python3Shim {
    param([Parameter(Mandatory = $true)][string]$Path)

    $shimContent = @"
@echo off
setlocal
where py >nul 2>nul
if not errorlevel 1 (
    py -3 %*
    exit /b %ERRORLEVEL%
)
where python >nul 2>nul
if not errorlevel 1 (
    python %*
    exit /b %ERRORLEVEL%
)
echo python3 shim could not find py or python on PATH. 1>&2
exit /b 9009
"@

    Ensure-Directory -Path (Split-Path -Parent $Path)
    Set-Content -LiteralPath $Path -Value ($shimContent.Trim() + "`r`n") -Encoding ASCII
}

function Install-PiLensCliTools {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    Ensure-Directory -Path $PiLensToolsDir

    $packageJsonPath = Join-Path $PiLensToolsDir 'package.json'
    if (-not (Test-Path -LiteralPath $packageJsonPath)) {
        $packageJson = [ordered]@{
            name    = 'pi-lens-tools'
            private = $true
        }
        Save-JsonObject -Path $packageJsonPath -Data $packageJson
    }

    $tools = @(
        @{ Package = '@ast-grep/cli'; Binary = 'sg.cmd'; VerifyArgs = @('--version') },
        @{ Package = 'knip'; Binary = 'knip.cmd'; VerifyArgs = @('--version') },
        @{ Package = 'jscpd'; Binary = 'jscpd.cmd'; VerifyArgs = @('--version') },
        @{ Package = 'madge'; Binary = 'madge.cmd'; VerifyArgs = @('--version') }
    )

    foreach ($tool in $tools) {
        Invoke-WithRetry -Description ("npm install {0} for pi-lens" -f $tool.Package) -Action {
            Invoke-External -FilePath $NpmExe -WorkingDirectory $PiLensToolsDir -Arguments @('install', '--no-audit', '--no-fund', $tool.Package)
        } -MaxAttempts 2 -DelaySeconds 5

        $binaryPath = Join-Path $PiLensToolsDir ("node_modules\.bin\" + $tool.Binary)
        if (-not (Test-Path -LiteralPath $binaryPath)) {
            throw "pi-lens tool install did not produce expected binary: $binaryPath"
        }

        Invoke-External -FilePath $binaryPath -WorkingDirectory $PiLensToolsDir -Arguments $tool.VerifyArgs
    }
}

function Repair-PiLensTooling {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    Write-Step 'Preparing pi-lens tooling on Windows'

    Ensure-Command -Name 'rg' -WingetPackageId 'BurntSushi.ripgrep.MSVC' -DisplayName 'ripgrep (rg)' -Optional | Out-Null
    Ensure-Command -Name 'fd' -WingetPackageId 'sharkdp.fd' -DisplayName 'fd' -Optional | Out-Null

    if (Test-Path -LiteralPath $PiLensToolsDir) {
        try {
            Remove-Item -LiteralPath $PiLensToolsDir -Recurse -Force -ErrorAction Stop
            Write-Info "Removed stale pi-lens tools cache: $PiLensToolsDir"
        }
        catch {
            Write-Warning "Could not reset pi-lens tools cache '$PiLensToolsDir': $($_.Exception.Message)"
        }
    }

    try {
        Install-PiLensCliTools -NpmExe $NpmExe
    }
    catch {
        Write-Warning "Could not fully preinstall pi-lens CLI tools: $($_.Exception.Message)"
    }
}

function Get-PiRelatedRunningProcesses {
    $results = @()
    try {
        $processes = Get-CimInstance Win32_Process -ErrorAction Stop | Where-Object {
            $_.Name -match '^(node|npm|powershell|pwsh|cmd|bash)(\.exe)?$'
        }

        foreach ($process in $processes) {
            $commandLine = [string]$process.CommandLine
            if ($commandLine -match 'pi-coding-agent|\\npm\\pi\.(cmd|ps1)\b') {
                $results += [PSCustomObject]@{
                    ProcessId   = $process.ProcessId
                    Name        = $process.Name
                    CommandLine = $commandLine
                }
            }
        }
    }
    catch {
        Write-Warning "Could not inspect running processes: $($_.Exception.Message)"
    }

    return @($results)
}

function Warn-AboutPiRelatedProcesses {
    $processes = @(Get-PiRelatedRunningProcesses)
    if ($processes.Count -eq 0) {
        return
    }

    Write-Warning 'Detected running pi/npm/node-related processes. On Windows these can lock files and cause npm EPERM cleanup/install issues.'
    foreach ($process in $processes | Select-Object -First 5) {
        Write-Warning ("PID {0} {1}: {2}" -f $process.ProcessId, $process.Name, $process.CommandLine)
    }
    if ($processes.Count -gt 5) {
        Write-Warning ("... and {0} more process(es)." -f ($processes.Count - 5))
    }
}

function Remove-StaleGlobalPiCodingAgent {
    param([Parameter(Mandatory = $true)][string]$NpmExe)
    $appData = [Environment]::GetFolderPath('ApplicationData')
    $shimCandidates = @(
        (Join-Path $appData 'npm\pi.ps1'),
        (Join-Path $appData 'npm\pi.cmd'),
        (Join-Path $appData 'npm\pi')
    )

    Warn-AboutPiRelatedProcesses

    try {
        Invoke-External -FilePath $NpmExe -Arguments @('uninstall', '-g', '@mariozechner/pi-coding-agent', '--no-fund', '--no-audit')
    }
    catch {
        Write-Warning "Global uninstall cleanup failed: $($_.Exception.Message)"
    }

    foreach ($path in $shimCandidates) {
        if (-not $path) { continue }
        if (-not (Test-Path -LiteralPath $path)) { continue }
        try {
            Write-Info "Removing stale path: $path"
            Remove-Item -LiteralPath $path -Recurse -Force -ErrorAction Stop
        }
        catch {
            Write-Warning "Could not remove stale path '$path': $($_.Exception.Message)"
        }
    }
}

function Install-GlobalPiCodingAgent {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    Write-Step 'Installing or updating pi-coding-agent globally'
    Remove-StaleGlobalPiCodingAgent -NpmExe $NpmExe
    $packageSpecifier = if ([string]::IsNullOrWhiteSpace($AgentVersion)) {
        '@mariozechner/pi-coding-agent'
    }
    else {
        "@mariozechner/pi-coding-agent@$AgentVersion"
    }
    Invoke-WithRetry -Description "npm install -g $packageSpecifier" -Action {
        Invoke-External -FilePath $NpmExe -Arguments @('install', '-g', $packageSpecifier, '--no-fund', '--no-audit')
    } -MaxAttempts 3 -DelaySeconds 5
}

function Invoke-WingetProcess {
    param(
        [Parameter(Mandatory = $true)][string]$WingetPath,
        [Parameter(Mandatory = $true)][string[]]$Arguments,
        [int[]]$AcceptableExitCodes = @()
    )

    Write-Info ("Run: " + $WingetPath + ' ' + ($Arguments -join ' '))
    $process = Start-Process -FilePath $WingetPath -ArgumentList $Arguments -Wait -NoNewWindow -PassThru
    $exitCode = $process.ExitCode
    if ($exitCode -ne 0 -and $AcceptableExitCodes -notcontains $exitCode) {
        throw "Command failed ($exitCode): $WingetPath $($Arguments -join ' ')"
    }
}

function Invoke-WingetInstall {
    param(
        [Parameter(Mandatory = $true)][string]$PackageId,
        [Parameter(Mandatory = $true)][string]$DisplayName
    )

    $winget = Get-CommandPathSafe -Name 'winget'
    if (-not $winget) {
        throw "'$DisplayName' is missing and winget is not available. Please install it manually."
    }

    Write-Step "Installing $DisplayName via winget"
    Invoke-WithRetry -Description "winget install $PackageId" -Action {
        Invoke-WingetProcess -WingetPath $winget -Arguments @(
            'install', '--id', $PackageId, '--exact', '--silent',
            '--accept-package-agreements', '--accept-source-agreements', '--disable-interactivity'
        )
    } -MaxAttempts 2 -DelaySeconds 5
    Refresh-ProcessPath
}

function Invoke-WingetUpgrade {
    param(
        [Parameter(Mandatory = $true)][string]$PackageId,
        [Parameter(Mandatory = $true)][string]$DisplayName
    )

    $winget = Get-CommandPathSafe -Name 'winget'
    if (-not $winget) {
        Write-Warning "winget is not available, so '$DisplayName' could not be checked for updates."
        return
    }

    # 0x8A15002B = WINGET_NO_APPLICABLE_UPGRADE (already up to date)
    $noUpgradeExitCode = -1978335189

    Write-Step "Checking for updates for $DisplayName via winget"
    try {
        Invoke-WithRetry -Description "winget upgrade $PackageId" -Action {
            Invoke-WingetProcess -WingetPath $winget -Arguments @(
                'upgrade', '--id', $PackageId, '--exact', '--silent',
                '--accept-package-agreements', '--accept-source-agreements', '--disable-interactivity',
                '--include-unknown'
            ) -AcceptableExitCodes @($noUpgradeExitCode)
        } -MaxAttempts 2 -DelaySeconds 5
        Refresh-ProcessPath
    }
    catch {
        Write-Warning "Could not update '$DisplayName' via winget: $($_.Exception.Message)"
    }
}

function Ensure-Command {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [string]$WingetPackageId,
        [string]$DisplayName = $Name,
        [switch]$Optional
    )

    if (Test-CommandExists -Name $Name) {
        if ($WingetPackageId -and $UpdatePrerequisites) {
            Invoke-WingetUpgrade -PackageId $WingetPackageId -DisplayName $DisplayName
        }
        return (Get-CommandPathSafe -Name $Name)
    }

    if ($WingetPackageId) {
        try {
            Invoke-WingetInstall -PackageId $WingetPackageId -DisplayName $DisplayName
        }
        catch {
            if ($Optional) {
                Write-Warning $_.Exception.Message
                return $null
            }
            throw
        }

        if (Test-CommandExists -Name $Name) {
            return (Get-CommandPathSafe -Name $Name)
        }
    }

    if ($Optional) {
        Write-Warning "'$DisplayName' was not found."
        return $null
    }

    throw "'$DisplayName' was not found."
}

function Get-NpmExecutable {
    $npmCmd = Get-CommandPathSafe -Name 'npm.cmd'
    if ($npmCmd) { return $npmCmd }

    $npm = Get-CommandPathSafe -Name 'npm'
    if ($npm) { return $npm }

    return $null
}

function Get-PiExecutable {
    param([string]$NpmExe)

    if ($NpmExe) {
        try {
            $prefixText = (& $NpmExe 'prefix' '-g' 2>$null | Out-String).Trim()
            if (-not [string]::IsNullOrWhiteSpace($prefixText)) {
                $prefixPath = $prefixText.Split([Environment]::NewLine)[-1].Trim()
                if (-not [string]::IsNullOrWhiteSpace($prefixPath)) {
                    $piCmd = Join-Path $prefixPath 'pi.cmd'
                    if (Test-Path -LiteralPath $piCmd) {
                        return $piCmd
                    }
                }
            }
        }
        catch {
        }
    }

    $appData = [Environment]::GetFolderPath('ApplicationData')
    $fallbackPiCmd = Join-Path $appData 'npm\pi.cmd'
    if (Test-Path -LiteralPath $fallbackPiCmd) {
        return $fallbackPiCmd
    }

    $piCmdResolved = Get-CommandPathSafe -Name 'pi.cmd'
    if ($piCmdResolved) { return $piCmdResolved }

    $pi = Get-CommandPathSafe -Name 'pi'
    if ($pi) { return $pi }

    return $null
}

function ConvertTo-HashtableCompatible {
    param($InputObject)

    if ($null -eq $InputObject) {
        return $null
    }

    if ($InputObject -is [System.Collections.IDictionary]) {
        $result = [ordered]@{}
        foreach ($key in $InputObject.Keys) {
            $result[$key] = ConvertTo-HashtableCompatible -InputObject $InputObject[$key]
        }
        return $result
    }

    if (($InputObject -is [System.Collections.IEnumerable]) -and ($InputObject -isnot [string])) {
        $result = @()
        foreach ($item in $InputObject) {
            $result += ,(ConvertTo-HashtableCompatible -InputObject $item)
        }
        return $result
    }

    if ($InputObject -is [psobject]) {
        $properties = @($InputObject.PSObject.Properties | Where-Object { $_.MemberType -like '*Property' })
        if ($properties.Count -gt 0) {
            $result = [ordered]@{}
            foreach ($property in $properties) {
                $result[$property.Name] = ConvertTo-HashtableCompatible -InputObject $property.Value
            }
            return $result
        }
    }

    return $InputObject
}

function Load-JsonObject {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        return @{}
    }

    $raw = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    if ([string]::IsNullOrWhiteSpace($raw)) {
        return @{}
    }

    $convertFromJsonCommand = Get-Command ConvertFrom-Json -ErrorAction Stop
    if ($convertFromJsonCommand.Parameters.ContainsKey('AsHashtable')) {
        $obj = $raw | ConvertFrom-Json -AsHashtable
    }
    else {
        $obj = ConvertTo-HashtableCompatible -InputObject ($raw | ConvertFrom-Json)
    }

    if ($null -eq $obj) {
        return @{}
    }

    return $obj
}

function Save-JsonObject {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)]$Data
    )

    Ensure-Directory -Path (Split-Path -Parent $Path)
    $json = $Data | ConvertTo-Json -Depth 100
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, ($json + "`n"), $utf8NoBom)
}

function Backup-IfExists {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        return
    }

    Ensure-Directory -Path $SettingsBackupDir
    $timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
    $target = Join-Path $SettingsBackupDir ((Split-Path -Leaf $Path) + '.' + $timestamp + '.bak')
    Copy-Item -LiteralPath $Path -Destination $target -Force
    Write-Info "Backup created: $target"
}

function Merge-UniqueStrings {
    param(
        [object[]]$Existing,
        [object[]]$Incoming
    )

    $list = New-Object System.Collections.Generic.List[string]
    $seen = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

    foreach ($item in @($Existing) + @($Incoming)) {
        if ($null -eq $item) { continue }
        $text = [string]$item
        if ([string]::IsNullOrWhiteSpace($text)) { continue }
        if ($seen.Add($text)) {
            $list.Add($text)
        }
    }

    return @($list)
}

function Get-GitBashPath {
    $candidates = New-Object System.Collections.Generic.List[string]

    foreach ($baseDir in @($env:ProgramFiles, ${env:ProgramFiles(x86)})) {
        if ([string]::IsNullOrWhiteSpace($baseDir)) { continue }
        $candidates.Add((Join-Path $baseDir 'Git\bin\bash.exe'))
    }

    $gitPath = Get-CommandPathSafe -Name 'git'
    if ($gitPath) {
        $gitCmdDir = Split-Path -Parent $gitPath
        $gitRootDir = Split-Path -Parent $gitCmdDir
        if (-not [string]::IsNullOrWhiteSpace($gitRootDir)) {
            $candidates.Add((Join-Path $gitRootDir 'bin\bash.exe'))
        }
    }

    foreach ($candidate in $candidates) {
        if (Test-Path -LiteralPath $candidate) {
            return $candidate
        }
    }

    $bash = Get-CommandPathSafe -Name 'bash'
    if ($bash) { return $bash }
    return $null
}

function Get-PowerShellExecutablePath {
    $currentShellPath = Get-CommandPathSafe -Name 'powershell'
    if ($currentShellPath) {
        return $currentShellPath
    }

    $systemRoot = [Environment]::GetEnvironmentVariable('SystemRoot')
    if (-not [string]::IsNullOrWhiteSpace($systemRoot)) {
        $fallback = Join-Path $systemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
        if (Test-Path -LiteralPath $fallback) {
            return $fallback
        }
    }

    return 'powershell.exe'
}

function Get-PiPackageSources {
    $sources = @()
    foreach ($name in $PackageNames) {
        $sources += ("npm:{0}" -f $name)
    }
    return $sources
}

function Test-PiAuthenticated {
    if (-not (Test-Path -LiteralPath $GlobalPiAgentAuthPath)) {
        return $false
    }

    try {
        $raw = Get-Content -LiteralPath $GlobalPiAgentAuthPath -Raw -Encoding UTF8
        return -not [string]::IsNullOrWhiteSpace($raw)
    }
    catch {
        Write-Warning "Could not inspect Pi auth state at '$GlobalPiAgentAuthPath': $($_.Exception.Message)"
        return $false
    }
}

function Start-PiLoginIfNeeded {
    param(
        [Parameter(Mandatory = $true)][string]$PiExecutablePath,
        [Parameter(Mandatory = $true)][string]$WorkingDirectory,
        [Parameter(Mandatory = $true)][string]$StartScriptPath
    )

    if (Test-PiAuthenticated) {
        Write-Info 'Pi authentication already present. Skipping automatic login.'
        return
    }

    Write-Step 'Pi authentication required'
    Write-Warning 'No existing Pi authentication was found.'
    Write-Host 'Pi does not provide a non-interactive login flag for this flow.' -ForegroundColor Yellow
    Write-Host 'Start Pi and then run /login inside the Pi prompt.' -ForegroundColor Yellow
    Write-Host ''
    Write-Host 'Recommended command:' -ForegroundColor Yellow
    Write-Host ("  powershell -ExecutionPolicy Bypass -File `"{0}`"" -f $StartScriptPath) -ForegroundColor Yellow
    Write-Host 'Then type: /login' -ForegroundColor Yellow

    if (Test-Path -LiteralPath $StartScriptPath) {
        Write-Info 'Opening a new PowerShell window for Pi login.'
        try {
            Start-Process -FilePath (Get-PowerShellExecutablePath) -ArgumentList @(
                '-NoExit',
                '-ExecutionPolicy',
                'Bypass',
                '-File',
                $StartScriptPath
            ) | Out-Null
        }
        catch {
            Write-Warning "Could not open a new PowerShell window automatically: $($_.Exception.Message)"
        }
    }
}

function Install-TwinCATAdsPackage {
    param([Parameter(Mandatory = $true)][string]$PiExecutablePath)

    $source = if ([string]::IsNullOrWhiteSpace($TwinCATAdsSource)) {
        'npm:pi-twincat-ads'
    }
    else {
        (Resolve-Path -LiteralPath $TwinCATAdsSource -ErrorAction Stop).Path
    }

    $description = if ([string]::IsNullOrWhiteSpace($TwinCATAdsSource)) {
        'pi install npm:pi-twincat-ads -l'
    }
    else {
        'pi install local pi-twincat-ads source -l'
    }

    $label = if ([string]::IsNullOrWhiteSpace($TwinCATAdsSource)) {
        'Installing pi-twincat-ads from npm'
    }
    else {
        'Installing pi-twincat-ads from local path'
    }

    Write-Step $label
    Invoke-WithRetry -Description $description -Action {
        Invoke-External -FilePath $PiExecutablePath -WorkingDirectory $ResolvedProjectRoot -Arguments @('install', $source, '--local')
    } -MaxAttempts 3 -DelaySeconds 5
}

function Install-PiPackages {
    param([Parameter(Mandatory = $true)][string]$PiExecutablePath)

    Write-Step 'Installing local Pi packages via pi install'
    foreach ($source in Get-PiPackageSources) {
        Invoke-WithRetry -Description ("pi install {0} -l" -f $source) -Action {
            Invoke-External -FilePath $PiExecutablePath -WorkingDirectory $ResolvedProjectRoot -Arguments @('install', $source, '--local')
        } -MaxAttempts 3 -DelaySeconds 5
    }
}

Ensure-Directory -Path $PiDir
Ensure-Directory -Path $ShimDir
Ensure-Directory -Path $LogsDir

try {
    try {
        Start-Transcript -Path $InstallLogPath -Force | Out-Null
        $TranscriptStarted = $true
    }
    catch {
        Write-Warning "Could not start transcript: $($_.Exception.Message)"
    }

    Write-Info "Install log: $InstallLogPath"
    Write-Step 'Checking and installing prerequisites'

    if (-not $IsWindowsPlatform) {
        throw 'This bootstrap script is intended for Windows.'
    }

    $nodePath = Ensure-Command -Name 'node' -WingetPackageId 'OpenJS.NodeJS.LTS' -DisplayName 'Node.js LTS'
    $npmPath = Ensure-Command -Name 'npm' -WingetPackageId 'OpenJS.NodeJS.LTS' -DisplayName 'npm'
    $npmExe = Get-NpmExecutable
    if (-not $npmExe) {
        throw 'Could not resolve npm.'
    }

    Write-Host "node: $(& $nodePath --version)"
    Write-Host "npm:  $(& $npmExe --version)"

    $gitBashPath = Get-GitBashPath
    if (-not $gitBashPath) {
        Ensure-Command -Name 'git' -WingetPackageId 'Git.Git' -DisplayName 'Git for Windows'
        $gitBashPath = Get-GitBashPath
    }

    if ($gitBashPath) {
        Write-Host "bash: $gitBashPath"
    } else {
        throw 'No bash shell found. Pi needs Git Bash or another bash.exe on Windows.'
    }

    if (-not [string]::IsNullOrWhiteSpace($TwinCATAdsSource) -and -not $IncludeTwinCATAds) {
        Write-Info 'TwinCATAdsSource was provided without IncludeTwinCATAds. Treating the source path as an implicit TwinCAT enable.'
    }

    $pythonPath = Get-CommandPathSafe -Name 'py'
    if (-not $pythonPath) {
        $pythonPath = Get-CommandPathSafe -Name 'python'
    }

    if (-not $pythonPath) {
        $pythonPath = Ensure-Command -Name 'py' -WingetPackageId 'Python.Python.3.12' -DisplayName 'Python Launcher' -Optional
        if (-not $pythonPath) {
            $pythonPath = Get-CommandPathSafe -Name 'python'
        }
        if (-not $pythonPath) {
            $pythonPath = Ensure-Command -Name 'python' -WingetPackageId 'Python.Python.3.12' -DisplayName 'Python 3'
        }
    }

    if (-not $pythonPath) {
        throw 'Python is required for mempalace-pi but could not be installed or found.'
    }

    Refresh-ProcessPath

    try {
        Write-Host "python: $(& $pythonPath --version 2>&1)"
    }
    catch {
        Write-Warning "Python was found, but its version could not be read: $($_.Exception.Message)"
    }

    Install-MemPalacePythonBackend -PythonPath $pythonPath
    Write-Step 'Writing python3 compatibility shim for Windows'
    Write-Python3Shim -Path $PythonShimPath
    Repair-PiLensTooling -NpmExe $npmExe

    Install-GlobalPiCodingAgent -NpmExe $npmExe
    Refresh-ProcessPath

    $piExe = Get-PiExecutable -NpmExe $npmExe
    if (-not $piExe) {
        throw 'pi was not found after the global npm install.'
    }

    Write-Host "pi:   $(& $piExe --version)"

    Write-Step 'Preparing project structure'
    Ensure-Directory -Path $ProjectScriptsDir

    Install-PiPackages -PiExecutablePath $piExe
    if ($IncludeTwinCATAds -or -not [string]::IsNullOrWhiteSpace($TwinCATAdsSource)) {
        Install-TwinCATAdsPackage -PiExecutablePath $piExe
    }

    Write-Step 'Writing robust Pi project configuration'
    Backup-IfExists -Path $SettingsPath
    $settings = Load-JsonObject -Path $SettingsPath

    $settings['npmCommand'] = @('npm.cmd')
    $settings['shellPath'] = $gitBashPath
    $settings['sessionDir'] = '.pi/sessions'
    Save-JsonObject -Path $SettingsPath -Data $settings

    Write-Step 'Writing start script for mempalace/Python UTF-8'
    $startScript = @"
param(
    [Parameter(ValueFromRemainingArguments = `$true)]
    [string[]]`$PiArgs
)

`$ErrorActionPreference = 'Stop'
`$env:PYTHONUTF8 = '1'
`$env:PYTHONIOENCODING = 'utf-8'

`$ScriptDir = Split-Path -Parent `$MyInvocation.MyCommand.Path
`$ProjectRoot = Split-Path -Parent `$ScriptDir
`$ShimDir = Join-Path `$ProjectRoot '.pi\bin'
if (Test-Path -LiteralPath `$ShimDir) {
    `$env:Path = `$ShimDir + ';' + `$env:Path
}
Set-Location `$ProjectRoot

`$piCmd = Get-Command 'pi' -ErrorAction SilentlyContinue
`$piCmdPath = if (`$piCmd) { `$piCmd.Source } else { `$null }
if (-not `$piCmdPath) {
    `$piFallback = Join-Path ([Environment]::GetFolderPath('ApplicationData')) 'npm\pi.cmd'
    if (Test-Path -LiteralPath `$piFallback) {
        `$piCmdPath = `$piFallback
    }
}

if (-not `$piCmdPath) {
    throw 'pi was not found. Please run scripts/install-pi-stack.ps1 first.'
}

& `$piCmdPath @PiArgs
exit `$LASTEXITCODE
"@
    Set-Content -LiteralPath $StartScriptPath -Value $startScript -Encoding UTF8

    Write-Step 'Writing AGENTS.md'
    $agentsMdPath = Join-Path $ResolvedProjectRoot 'AGENTS.md'
    $agentsMdContent = Get-AgentsMdContent
    Set-GeneratedAgentsSection -Path $agentsMdPath -GeneratedContent $agentsMdContent
    Write-Info "AGENTS.md: $agentsMdPath"

    Write-Step 'Done'
    Write-Host 'Successfully prepared:' -ForegroundColor Green
    Write-Host "  - Project root: $ResolvedProjectRoot"
    Write-Host "  - Global: @mariozechner/pi-coding-agent"
    foreach ($packageName in $PackageNames) {
        Write-Host "  - Local:  $packageName"
    }
    if ($IncludeTwinCATAds -or -not [string]::IsNullOrWhiteSpace($TwinCATAdsSource)) {
        Write-Host '  - Local:  pi-twincat-ads'
    }

    Write-Host "`nImportant files:"
    Write-Host "  - $SettingsPath"
    Write-Host "  - $StartScriptPath"
    Write-Host "  - $agentsMdPath"
    Write-Host "  - $InstallerScriptPath"
    Write-Host "  - $InstallLogPath"

    Write-Host "`nRecommended startup on Windows from the target repo:"
    Write-Host "  powershell -ExecutionPolicy Bypass -File .\scripts\start-pi.ps1"
    Write-Host "  # target repo: $ResolvedProjectRoot"

    Start-PiLoginIfNeeded -PiExecutablePath $piExe -WorkingDirectory $ResolvedProjectRoot -StartScriptPath $StartScriptPath
}
catch {
    $ScriptExitCode = 1
    Write-ErrorLine $_.Exception.Message
    Write-Host "Log file: $InstallLogPath" -ForegroundColor Yellow
}
finally {
    if ($TranscriptStarted) {
        try {
            Stop-Transcript | Out-Null
        }
        catch {
        }
    }
}

exit $ScriptExitCode
