[CmdletBinding()]
param(
    [string]$InstallRoot = (Join-Path ([Environment]::GetFolderPath('UserProfile')) '.pi-stack'),
    [switch]$IncludeTwinCATAds,
    [string]$TwinCATAdsSource,
    [switch]$RequirePython,
    [switch]$UseLatestPackageVersions
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$IsWindowsPlatform = if (Get-Variable -Name 'IsWindows' -ErrorAction SilentlyContinue) {
    [bool]$IsWindows
}
else {
    ($PSVersionTable.PSEdition -eq 'Desktop') -or ([Environment]::OSVersion.Platform -eq [PlatformID]::Win32NT)
}

$TranscriptStarted = $false
$ScriptExitCode = 0
$ResolvedInstallRoot = $null
$GlobalScriptPath = if ($MyInvocation.MyCommand.Path) { $MyInvocation.MyCommand.Path } else { $PSCommandPath }
$UserProfilePath = [Environment]::GetFolderPath('UserProfile')
$GlobalPiAgentDir = Join-Path $UserProfilePath '.pi\agent'
$GlobalPiAgentSettingsPath = Join-Path $GlobalPiAgentDir 'settings.json'
$GlobalPiAgentBackupsDir = Join-Path $GlobalPiAgentDir 'backups'
$GlobalAgentsDir = Join-Path $UserProfilePath '.pi\agents'
$GlobalAgentsPath = Join-Path $GlobalAgentsDir 'AGENTS.md'

$PinnedVersions = [ordered]@{
    'mempalace-pi'   = '0.2.0'
    'pi-lens'        = '3.8.26'
    'pi-mcp-adapter' = '2.4.0'
    'pi-subagents'   = '0.14.1'
    'pi-web-access'  = '0.10.6'
}

# Intentionally pinned: npm currently resolves the latest pi-coding-agent release
# to @mariozechner/pi-ai@^0.67.4, but that package version is not published.
$GlobalPiCodingAgentVersion = '0.67.3'

$PackageNames = @($PinnedVersions.Keys)

function Write-Step {
    param([Parameter(Mandatory = $true)][string]$Message)
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

function Write-Info {
    param([Parameter(Mandatory = $true)][string]$Message)
    Write-Host "[info] $Message" -ForegroundColor DarkGray
}

function Write-ErrorLine {
    param([Parameter(Mandatory = $true)][string]$Message)
    Write-Host "[error] $Message" -ForegroundColor Red
}

function Ensure-Directory {
    param([Parameter(Mandatory = $true)][string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

function Set-GeneratedAgentsSection {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$GeneratedContent
    )

    $beginMarker = '<!-- BEGIN PI-SETUP-AUTOGENERATED -->'
    $endMarker = '<!-- END PI-SETUP-AUTOGENERATED -->'
    $block = $beginMarker + "`r`n" + $GeneratedContent.Trim() + "`r`n" + $endMarker + "`r`n"

    $existing = ''
    if (Test-Path -LiteralPath $Path) {
        $existing = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    }

    if ($existing -match [regex]::Escape($beginMarker) + '[\s\S]*?' + [regex]::Escape($endMarker)) {
        $updated = [regex]::Replace($existing, [regex]::Escape($beginMarker) + '[\s\S]*?' + [regex]::Escape($endMarker), $block.TrimEnd())
        Set-Content -LiteralPath $Path -Value ($updated.TrimEnd() + "`r`n") -Encoding UTF8
        return
    }

    $prefix = @"
# AGENTS.md

This file contains instructions for coding agents working with this Pi installation.

"@

    if ([string]::IsNullOrWhiteSpace($existing)) {
        Set-Content -LiteralPath $Path -Value ($prefix + $block) -Encoding UTF8
    }
    else {
        $separator = if ($existing.EndsWith("`n")) { "" } else { "`r`n" }
        Set-Content -LiteralPath $Path -Value ($existing + $separator + "`r`n" + $block) -Encoding UTF8
    }
}

function Get-AgentsMdContent {
    param([switch]$IncludeTwinCATAds)

    $twincatSection = if ($IncludeTwinCATAds) {
@"
- `pi-twincat-ads`: Use for TwinCAT ADS communication and related automation tasks when the project requires it.
"@
    }
    else { '' }

    return @"
## Pi setup tools available globally

Installed Pi packages:
- `pi-lens`: Prefer this for code understanding, LSP navigation, references, definitions, hover info, AST-aware search, and precise code changes.
- `mempalace-pi`: Treat this as a core part of the workflow. Use it actively for memory workflows, persistent project knowledge, reminders, decisions, follow-ups, and important discoveries that should survive the current session.
- `pi-subagents`: Use subagents when a task benefits from decomposition, parallel exploration, or specialized analysis.
- `pi-mcp-adapter`: Use MCP servers/tools when project tasks require external integrations or structured tool access.
- `pi-web-access`: Use web search/fetch only for external documentation or information not available in the repository.
$twincatSection
## Agent usage guidance

- Start with local repository context first, but assume these globally installed Pi tools may be available across repositories and editors.
- Use `mempalace-pi` as an active workflow component, not just as optional storage.
- When you learn something likely to matter later, store it in `mempalace-pi`.
- Before or during complex work, consider whether relevant prior knowledge from `mempalace-pi` may exist.
- Prefer `pi-lens`/LSP and AST-aware search over plain text search when navigating or modifying code.
- Use `pi-subagents` only when the task is complex enough to benefit from delegation.
- Use `pi-mcp-adapter` and `pi-web-access` deliberately, not by default.
- Keep edits minimal, precise, and consistent with each repository's existing structure.
- When changing behavior, also update nearby documentation and scripts if needed.
- For Python-backed features such as `mempalace-pi` on Windows, prefer the provided start scripts and UTF-8 environment settings.

## Global project note

This `AGENTS.md` section was generated by `scripts/install-pi-stack-global.ps1`.
You may add custom instructions outside the autogenerated block.
"@
}

function Refresh-ProcessPath {
    $machinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    $combined = @($machinePath, $userPath) -join ';'
    if (-not [string]::IsNullOrWhiteSpace($combined)) {
        $env:Path = $combined
    }
}

function Get-CommandPathSafe {
    param([Parameter(Mandatory = $true)][string]$Name)
    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    return $null
}

function Test-CommandExists {
    param([Parameter(Mandatory = $true)][string]$Name)
    return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Invoke-External {
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [string[]]$Arguments = @(),
        [string]$WorkingDirectory
    )

    if ($WorkingDirectory) { Push-Location $WorkingDirectory }
    try {
        Write-Info ("Run: " + $FilePath + ' ' + ($Arguments -join ' '))
        & $FilePath @Arguments
        $exitCode = $LASTEXITCODE
        if ($exitCode -ne 0) {
            throw "Command failed ($exitCode): $FilePath $($Arguments -join ' ')"
        }
    }
    finally {
        if ($WorkingDirectory) { Pop-Location }
    }
}

function Invoke-WithRetry {
    param(
        [Parameter(Mandatory = $true)][scriptblock]$Action,
        [Parameter(Mandatory = $true)][string]$Description,
        [int]$MaxAttempts = 3,
        [int]$DelaySeconds = 4
    )

    $attempt = 0
    while ($attempt -lt $MaxAttempts) {
        $attempt++
        try {
            Write-Info "$Description (attempt $attempt/$MaxAttempts)"
            & $Action
            return
        }
        catch {
            if ($attempt -ge $MaxAttempts) { throw }
            Write-Warning "$Description failed: $($_.Exception.Message)"
            Write-Info "Waiting $DelaySeconds seconds before the next attempt ..."
            Start-Sleep -Seconds $DelaySeconds
        }
    }
}

function Get-PythonCommandSpec {
    param([Parameter(Mandatory = $true)][string]$PythonPath)

    $leaf = Split-Path -Leaf $PythonPath
    $baseArguments = @()
    if ($leaf -ieq 'py.exe' -or $leaf -ieq 'py') {
        $baseArguments += '-3'
    }

    return [ordered]@{
        FilePath      = $PythonPath
        BaseArguments = $baseArguments
    }
}

function Invoke-PythonCommand {
    param(
        [Parameter(Mandatory = $true)][string]$PythonPath,
        [Parameter(Mandatory = $true)][string[]]$Arguments,
        [string]$WorkingDirectory
    )

    $pythonSpec = Get-PythonCommandSpec -PythonPath $PythonPath
    $allArguments = @($pythonSpec['BaseArguments']) + @($Arguments)
    Invoke-External -FilePath $pythonSpec['FilePath'] -Arguments $allArguments -WorkingDirectory $WorkingDirectory
}

function Install-MemPalacePythonBackend {
    param([Parameter(Mandatory = $true)][string]$PythonPath)

    $env:PYTHONUTF8 = '1'
    $env:PYTHONIOENCODING = 'utf-8'

    Write-Step 'Installing MemPalace Python backend'
    Invoke-WithRetry -Description 'python -m pip install --upgrade mempalace' -Action {
        Invoke-PythonCommand -PythonPath $PythonPath -Arguments @('-m', 'pip', 'install', '--upgrade', 'mempalace')
    } -MaxAttempts 3 -DelaySeconds 5

    Write-Step 'Validating MemPalace Python backend'
    Invoke-PythonCommand -PythonPath $PythonPath -Arguments @('-c', 'import mempalace; import mempalace.mcp_server')
}

function Get-NpmViewText {
    param(
        [Parameter(Mandatory = $true)][string]$NpmExe,
        [Parameter(Mandatory = $true)][string[]]$Arguments
    )

    $output = & $NpmExe @Arguments 2>$null
    if ($LASTEXITCODE -ne 0) {
        return $null
    }

    $text = ($output | Out-String).Trim()
    if ([string]::IsNullOrWhiteSpace($text)) {
        return $null
    }

    return $text
}

function Get-NpmViewJson {
    param(
        [Parameter(Mandatory = $true)][string]$NpmExe,
        [Parameter(Mandatory = $true)][string[]]$Arguments
    )

    $text = Get-NpmViewText -NpmExe $NpmExe -Arguments $Arguments
    if ([string]::IsNullOrWhiteSpace($text)) {
        return $null
    }

    try {
        return ($text | ConvertFrom-Json)
    }
    catch {
        return $null
    }
}

function Test-NpmPackageVersionExists {
    param(
        [Parameter(Mandatory = $true)][string]$NpmExe,
        [Parameter(Mandatory = $true)][string]$PackageName,
        [Parameter(Mandatory = $true)][string]$Version
    )

    $result = & $NpmExe 'view' ("$PackageName@$Version") 'version' '--json' 2>$null
    if ($LASTEXITCODE -ne 0) {
        return $false
    }

    $text = ($result | Out-String).Trim().Trim('"')
    return $text -eq $Version
}

function Get-GlobalNpmRoot {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    $text = Get-NpmViewText -NpmExe $NpmExe -Arguments @('root', '-g')
    if ([string]::IsNullOrWhiteSpace($text)) {
        return $null
    }

    return $text.Split([Environment]::NewLine)[0].Trim()
}

function Get-GlobalPiCodingAgentPath {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    $globalRoot = Get-GlobalNpmRoot -NpmExe $NpmExe
    if ([string]::IsNullOrWhiteSpace($globalRoot)) {
        return $null
    }

    return (Join-Path $globalRoot '@mariozechner\pi-coding-agent')
}

function Get-PiRelatedRunningProcesses {
    $results = @()
    try {
        $processes = Get-CimInstance Win32_Process -ErrorAction Stop | Where-Object {
            $_.Name -match '^(node|npm|powershell|pwsh|cmd|bash)(\.exe)?$'
        }

        foreach ($process in $processes) {
            $commandLine = [string]$process.CommandLine
            if ($commandLine -match 'pi-coding-agent|\\npm\\pi\.cmd|\bpi\b|\bnpm\b') {
                $results += [PSCustomObject]@{
                    ProcessId   = $process.ProcessId
                    Name        = $process.Name
                    CommandLine = $commandLine
                }
            }
        }
    }
    catch {
        Write-Warning "Could not inspect running processes: $($_.Exception.Message)"
    }

    return @($results)
}

function Warn-AboutPiRelatedProcesses {
    $processes = @(Get-PiRelatedRunningProcesses)
    if ($processes.Count -eq 0) {
        return
    }

    Write-Warning 'Detected running pi/npm/node-related processes. On Windows these can lock files and cause npm EPERM cleanup/install issues.'
    foreach ($process in $processes | Select-Object -First 5) {
        Write-Warning ("PID {0} {1}: {2}" -f $process.ProcessId, $process.Name, $process.CommandLine)
    }
    if ($processes.Count -gt 5) {
        Write-Warning ("... and {0} more process(es)." -f ($processes.Count - 5))
    }
}

function Remove-StaleGlobalPiCodingAgent {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    $packagePath = Get-GlobalPiCodingAgentPath -NpmExe $NpmExe
    $appData = [Environment]::GetFolderPath('ApplicationData')
    $shimCandidates = @(
        (Join-Path $appData 'npm\pi.cmd'),
        (Join-Path $appData 'npm\pi'),
        (Join-Path $appData 'npm\node_modules\@mariozechner\pi-coding-agent')
    )

    Warn-AboutPiRelatedProcesses

    try {
        Invoke-External -FilePath $NpmExe -Arguments @('uninstall', '-g', '@mariozechner/pi-coding-agent', '--no-fund', '--no-audit')
    }
    catch {
        Write-Warning "Global uninstall reported an issue: $($_.Exception.Message)"
    }

    foreach ($candidate in @($packagePath) + $shimCandidates) {
        if (-not [string]::IsNullOrWhiteSpace($candidate) -and (Test-Path -LiteralPath $candidate)) {
            try {
                Remove-Item -LiteralPath $candidate -Recurse -Force -ErrorAction Stop
                Write-Info "Removed stale path: $candidate"
            }
            catch {
                Write-Warning "Could not remove stale path '$candidate': $($_.Exception.Message)"
            }
        }
    }
}

function Install-GlobalPiCodingAgent {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    $packageVersion = $GlobalPiCodingAgentVersion
    if (-not (Test-NpmPackageVersionExists -NpmExe $NpmExe -PackageName '@mariozechner/pi-coding-agent' -Version $packageVersion)) {
        throw "Pinned version @mariozechner/pi-coding-agent@$packageVersion is not available on npm."
    }

    $versionJson = Get-NpmViewJson -NpmExe $NpmExe -Arguments @('view', '@mariozechner/pi-coding-agent', 'version', '--json')
    $latestInfo = if ($versionJson) { ($versionJson | Out-String).Trim() } else { 'unknown' }
    Write-Info "Installing @mariozechner/pi-coding-agent@$packageVersion (npm latest currently: $latestInfo)"

    Invoke-WithRetry -Description 'npm uninstall/install -g @mariozechner/pi-coding-agent' -Action {
        Remove-StaleGlobalPiCodingAgent -NpmExe $NpmExe
        Invoke-External -FilePath $NpmExe -Arguments @('install', '-g', ("@mariozechner/pi-coding-agent@{0}" -f $packageVersion), '--no-fund', '--no-audit')
    } -MaxAttempts 3 -DelaySeconds 5
}

function Invoke-WingetInstall {
    param(
        [Parameter(Mandatory = $true)][string]$PackageId,
        [Parameter(Mandatory = $true)][string]$DisplayName
    )

    $winget = Get-CommandPathSafe -Name 'winget'
    if (-not $winget) {
        throw "'$DisplayName' is missing and winget is not available. Please install it manually."
    }

    Write-Step "Installing $DisplayName via winget"
    Invoke-WithRetry -Description "winget install $PackageId" -Action {
        Invoke-External -FilePath $winget -Arguments @(
            'install', '--id', $PackageId, '--exact', '--silent',
            '--accept-package-agreements', '--accept-source-agreements', '--disable-interactivity'
        )
    } -MaxAttempts 2 -DelaySeconds 5
    Refresh-ProcessPath
}

function Ensure-Command {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [string]$WingetPackageId,
        [string]$DisplayName = $Name,
        [switch]$Optional
    )

    if (Test-CommandExists -Name $Name) {
        return (Get-CommandPathSafe -Name $Name)
    }

    if ($WingetPackageId) {
        try {
            Invoke-WingetInstall -PackageId $WingetPackageId -DisplayName $DisplayName
        }
        catch {
            if ($Optional) {
                Write-Warning $_.Exception.Message
                return $null
            }
            throw
        }

        if (Test-CommandExists -Name $Name) {
            return (Get-CommandPathSafe -Name $Name)
        }
    }

    if ($Optional) {
        Write-Warning "'$DisplayName' was not found."
        return $null
    }

    throw "'$DisplayName' was not found."
}

function Save-JsonObject {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)]$Data
    )

    Ensure-Directory -Path (Split-Path -Parent $Path)
    $json = $Data | ConvertTo-Json -Depth 100
    Set-Content -LiteralPath $Path -Value ($json + "`n") -Encoding UTF8
}

function ConvertTo-HashtableCompatible {
    param($InputObject)

    if ($null -eq $InputObject) {
        return $null
    }

    if ($InputObject -is [System.Collections.IDictionary]) {
        $result = [ordered]@{}
        foreach ($key in $InputObject.Keys) {
            $result[$key] = ConvertTo-HashtableCompatible -InputObject $InputObject[$key]
        }
        return $result
    }

    if (($InputObject -is [System.Collections.IEnumerable]) -and ($InputObject -isnot [string])) {
        $result = @()
        foreach ($item in $InputObject) {
            $result += ,(ConvertTo-HashtableCompatible -InputObject $item)
        }
        return $result
    }

    if ($InputObject -is [psobject]) {
        $properties = @($InputObject.PSObject.Properties | Where-Object { $_.MemberType -like '*Property' })
        if ($properties.Count -gt 0) {
            $result = [ordered]@{}
            foreach ($property in $properties) {
                $result[$property.Name] = ConvertTo-HashtableCompatible -InputObject $property.Value
            }
            return $result
        }
    }

    return $InputObject
}

function Load-JsonObject {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        return [ordered]@{}
    }

    $raw = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    if ([string]::IsNullOrWhiteSpace($raw)) {
        return [ordered]@{}
    }

    try {
        $convertFromJsonCommand = Get-Command ConvertFrom-Json -ErrorAction Stop
        if ($convertFromJsonCommand.Parameters.ContainsKey('AsHashtable')) {
            $parsed = $raw | ConvertFrom-Json -AsHashtable
        }
        else {
            $parsed = ConvertTo-HashtableCompatible -InputObject ($raw | ConvertFrom-Json)
        }

        if ($null -eq $parsed) {
            return [ordered]@{}
        }
        return $parsed
    }
    catch {
        throw "Could not parse JSON file '$Path': $($_.Exception.Message)"
    }
}

function Merge-UniqueStrings {
    param(
        $Existing,
        [string[]]$Incoming
    )

    $seen = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
    $result = New-Object System.Collections.Generic.List[string]

    foreach ($item in @($Existing) + @($Incoming)) {
        if ($item -isnot [string]) { continue }
        if ([string]::IsNullOrWhiteSpace($item)) { continue }
        if ($seen.Add($item)) {
            [void]$result.Add($item)
        }
    }

    return @($result)
}

function Get-NpmExecutable {
    $npmCmd = Get-CommandPathSafe -Name 'npm.cmd'
    if ($npmCmd) { return $npmCmd }
    $npm = Get-CommandPathSafe -Name 'npm'
    if ($npm) { return $npm }
    return $null
}

function Get-PiExecutable {
    $pi = Get-CommandPathSafe -Name 'pi'
    if ($pi) { return $pi }

    $appData = [Environment]::GetFolderPath('ApplicationData')
    $piCmd = Join-Path $appData 'npm\pi.cmd'
    if (Test-Path -LiteralPath $piCmd) {
        return $piCmd
    }

    return $null
}

function Get-GitBashPath {
    $candidates = @(
        'C:\Program Files\Git\bin\bash.exe',
        'C:\Program Files (x86)\Git\bin\bash.exe'
    )

    foreach ($candidate in $candidates) {
        if (Test-Path -LiteralPath $candidate) {
            return $candidate
        }
    }

    $bash = Get-CommandPathSafe -Name 'bash'
    if ($bash) { return $bash }
    return $null
}

function Get-DependencyMap {
    $dependencies = [ordered]@{}
    foreach ($name in $PackageNames) {
        $dependencies[$name] = if ($UseLatestPackageVersions) { 'latest' } else { $PinnedVersions[$name] }
    }
    return $dependencies
}

function Test-PackageInstalled {
    param(
        [Parameter(Mandatory = $true)][string]$PackagesDir,
        [Parameter(Mandatory = $true)][string]$PackageName
    )

    $packagePath = Join-Path $PackagesDir (Join-Path 'node_modules' $PackageName)
    return (Test-Path -LiteralPath $packagePath)
}

function Assert-PackageInstalled {
    param(
        [Parameter(Mandatory = $true)][string]$PackagesDir,
        [Parameter(Mandatory = $true)][string]$PackageName
    )

    if (-not (Test-PackageInstalled -PackagesDir $PackagesDir -PackageName $PackageName)) {
        throw "Package '$PackageName' was not installed under '$PackagesDir'."
    }
}

if (-not $IsWindowsPlatform) {
    throw 'This global script is intended for Windows.'
}

try {
    Ensure-Directory -Path $InstallRoot
    $ResolvedInstallRoot = (Resolve-Path -LiteralPath $InstallRoot).Path

    $PiDir = Join-Path $ResolvedInstallRoot '.pi'
    $PackagesDir = Join-Path $ResolvedInstallRoot '.pi-packages'
    $ScriptsDir = Join-Path $ResolvedInstallRoot 'scripts'
    $LogsDir = Join-Path $PiDir 'logs'
    $BackupsDir = Join-Path $PiDir 'backups'
    $SettingsPath = Join-Path $PiDir 'settings.json'
    $PackagesManifestPath = Join-Path $PackagesDir 'package.json'
    $StartScriptPath = Join-Path $ScriptsDir 'start-pi.ps1'
    $ReadmePath = Join-Path $ResolvedInstallRoot 'README-global-pi-stack.txt'
    $InstallLogPath = Join-Path $LogsDir ("global-install-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.log')

    Ensure-Directory -Path $PiDir
    Ensure-Directory -Path $PackagesDir
    Ensure-Directory -Path $ScriptsDir
    Ensure-Directory -Path $LogsDir
    Ensure-Directory -Path $BackupsDir
    Ensure-Directory -Path $GlobalPiAgentDir
    Ensure-Directory -Path $GlobalPiAgentBackupsDir
    Ensure-Directory -Path $GlobalAgentsDir

    try {
        Start-Transcript -Path $InstallLogPath -Force | Out-Null
        $TranscriptStarted = $true
    }
    catch {
        Write-Warning "Could not start transcript: $($_.Exception.Message)"
    }

    Write-Info "Install target: $ResolvedInstallRoot"
    Write-Info "Global Pi settings: $GlobalPiAgentSettingsPath"
    Write-Info "Install log: $InstallLogPath"

    Write-Step 'Checking and installing prerequisites'
    $nodePath = Ensure-Command -Name 'node' -WingetPackageId 'OpenJS.NodeJS.LTS' -DisplayName 'Node.js LTS'
    $npmExe = Get-NpmExecutable
    if (-not $npmExe) {
        throw 'npm was not found after installing Node.js.'
    }
    $gitPath = Ensure-Command -Name 'git' -WingetPackageId 'Git.Git' -DisplayName 'Git for Windows'
    $gitBashPath = Get-GitBashPath
    if (-not $gitBashPath) {
        throw 'Git Bash (bash.exe) was not found after installing Git for Windows.'
    }

    $pythonPath = Get-CommandPathSafe -Name 'py'
    if (-not $pythonPath) {
        $pythonPath = Get-CommandPathSafe -Name 'python'
    }

    if (-not $pythonPath) {
        $pythonPath = Ensure-Command -Name 'py' -WingetPackageId 'Python.Python.3.12' -DisplayName 'Python Launcher' -Optional
        if (-not $pythonPath) {
            $pythonPath = Get-CommandPathSafe -Name 'python'
        }
        if (-not $pythonPath) {
            $pythonPath = Ensure-Command -Name 'python' -WingetPackageId 'Python.Python.3.12' -DisplayName 'Python 3'
        }
    }

    if (-not $pythonPath) {
        throw 'Python is required for mempalace-pi but could not be installed or found.'
    }

    Write-Host "node: $(& $nodePath --version)"
    Write-Host "npm:  $(& $npmExe --version)"
    Write-Host "git:  $(& $gitPath --version)"
    Write-Host "bash: $gitBashPath"

    try {
        Write-Host "python: $(& $pythonPath --version 2>&1)"
    }
    catch {
        Write-Warning "Python was found, but its version could not be read: $($_.Exception.Message)"
    }

    Install-MemPalacePythonBackend -PythonPath $pythonPath

    Install-GlobalPiCodingAgent -NpmExe $npmExe
    Refresh-ProcessPath

    $piExe = Get-PiExecutable
    if (-not $piExe) {
        throw 'pi was not found after the global npm install.'
    }
    Write-Host "pi:   $(& $piExe --version)"

    Write-Step 'Creating local package manifest'
    $manifest = [ordered]@{
        name         = 'pi-setup-stack'
        private      = $true
        description  = 'Local Pi stack for this project'
        dependencies = (Get-DependencyMap)
    }
    Save-JsonObject -Path $PackagesManifestPath -Data $manifest

    Write-Step 'Installing local Pi packages via npm'
    Invoke-WithRetry -Description 'npm install for .pi-packages' -Action {
        Invoke-External -FilePath $npmExe -WorkingDirectory $PackagesDir -Arguments @('install', '--no-fund', '--no-audit')
    } -MaxAttempts 3 -DelaySeconds 5

    foreach ($packageName in $PackageNames) {
        Assert-PackageInstalled -PackagesDir $PackagesDir -PackageName $packageName
    }

    if ($IncludeTwinCATAds) {
        if ([string]::IsNullOrWhiteSpace($TwinCATAdsSource)) {
            throw 'If -IncludeTwinCATAds is set, -TwinCATAdsSource must also be provided.'
        }

        $resolvedTwinCATAds = (Resolve-Path -LiteralPath $TwinCATAdsSource -ErrorAction Stop).Path
        Write-Step 'Installing pi-twincat-ads from local path'
        Invoke-WithRetry -Description 'npm install pi-twincat-ads' -Action {
            Invoke-External -FilePath $npmExe -WorkingDirectory $PackagesDir -Arguments @('install', $resolvedTwinCATAds, '--no-fund', '--no-audit')
        } -MaxAttempts 3 -DelaySeconds 5
        Assert-PackageInstalled -PackagesDir $PackagesDir -PackageName 'pi-twincat-ads'
    }

    Write-Step 'Writing install-root and global Pi settings'
    $packagePaths = @(
        '../.pi-packages/node_modules/pi-subagents',
        '../.pi-packages/node_modules/pi-mcp-adapter',
        '../.pi-packages/node_modules/pi-lens',
        '../.pi-packages/node_modules/pi-web-access',
        '../.pi-packages/node_modules/mempalace-pi'
    )
    $globalPackagePaths = @(
        (Join-Path $PackagesDir 'node_modules\pi-subagents'),
        (Join-Path $PackagesDir 'node_modules\pi-mcp-adapter'),
        (Join-Path $PackagesDir 'node_modules\pi-lens'),
        (Join-Path $PackagesDir 'node_modules\pi-web-access'),
        (Join-Path $PackagesDir 'node_modules\mempalace-pi')
    )
    if ($IncludeTwinCATAds) {
        $packagePaths += '../.pi-packages/node_modules/pi-twincat-ads'
        $globalPackagePaths += (Join-Path $PackagesDir 'node_modules\pi-twincat-ads')
    }

    $installRootSettings = [ordered]@{
        npmCommand = @($npmExe)
        shellPath  = $gitBashPath
        packages   = $packagePaths
        sessionDir = '.pi/sessions'
    }
    Save-JsonObject -Path $SettingsPath -Data $installRootSettings

    if (Test-Path -LiteralPath $GlobalPiAgentSettingsPath) {
        $globalSettingsBackupPath = Join-Path $GlobalPiAgentBackupsDir ('settings-' + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.json.bak')
        Copy-Item -LiteralPath $GlobalPiAgentSettingsPath -Destination $globalSettingsBackupPath -Force
        Write-Info "Global Pi settings backup: $globalSettingsBackupPath"
    }

    $globalSettings = Load-JsonObject -Path $GlobalPiAgentSettingsPath
    $globalSettings['npmCommand'] = @($npmExe)
    $globalSettings['shellPath'] = $gitBashPath
    if (-not $globalSettings.ContainsKey('sessionDir') -or [string]::IsNullOrWhiteSpace([string]$globalSettings['sessionDir'])) {
        $globalSettings['sessionDir'] = '.pi/sessions'
    }
    $globalSettings['packages'] = Merge-UniqueStrings -Existing $globalSettings['packages'] -Incoming $globalPackagePaths
    Save-JsonObject -Path $GlobalPiAgentSettingsPath -Data $globalSettings

    Write-Step 'Writing start script'
    $startScript = @"
param(
    [Parameter(ValueFromRemainingArguments = `$true)]
    [string[]]`$PiArgs
)

`$ErrorActionPreference = 'Stop'
`$env:PYTHONUTF8 = '1'
`$env:PYTHONIOENCODING = 'utf-8'

`$ScriptDir = Split-Path -Parent `$MyInvocation.MyCommand.Path
`$ProjectRoot = Split-Path -Parent `$ScriptDir
Set-Location `$ProjectRoot

`$piCmd = Get-Command 'pi' -ErrorAction SilentlyContinue
`$piCmdPath = if (`$piCmd) { `$piCmd.Source } else { `$null }
if (-not `$piCmdPath) {
    `$piFallback = Join-Path ([Environment]::GetFolderPath('ApplicationData')) 'npm\pi.cmd'
    if (Test-Path -LiteralPath `$piFallback) {
        `$piCmdPath = `$piFallback
    }
}

if (-not `$piCmdPath) {
    throw 'pi was not found. Please run install-pi-stack-global.ps1 first.'
}

& `$piCmdPath @PiArgs
exit `$LASTEXITCODE
"@
    Set-Content -LiteralPath $StartScriptPath -Value $startScript -Encoding UTF8

    Write-Step 'Writing global install README'
    $readme = @'
Global Pi Setup Stack
=====================

This global Pi stack has been set up successfully.

Install root:
__INSTALL_ROOT__

What is included
----------------

- global @mariozechner/pi-coding-agent
- centrally installed Pi extensions in .pi-packages
- global Pi settings in %USERPROFILE%\.pi\agent\settings.json
- global agent guidance in %USERPROFILE%\.pi\agents\AGENTS.md
- install-root Pi settings in .pi\settings.json
- install-root Windows start script in scripts\start-pi.ps1
- install logs in .pi\logs\

Important files
---------------

- .pi\settings.json
- .pi-packages\package.json
- scripts\start-pi.ps1
- README-global-pi-stack.txt
- .pi\logs\
- %USERPROFILE%\.pi\agent\settings.json
- %USERPROFILE%\.pi\agents\AGENTS.md

Recommended usage
-----------------

To start Pi from this global install root:

powershell -ExecutionPolicy Bypass -File .\scripts\start-pi.ps1

You can also start Pi from other repos or editors that use the global Pi configuration.

Why use the start script?
-------------------------

The start script sets these environment variables for the current session:

- PYTHONUTF8=1
- PYTHONIOENCODING=utf-8

That is especially useful on Windows, in particular for mempalace-pi. The installer also provisions the Python `mempalace` backend so the MemPalace agent tools can run.

If something goes wrong
-----------------------

1. Check the latest file in .pi\logs\
2. Verify that pi, node, npm, and git are available
3. Confirm that Git Bash exists and that both .pi\settings.json and %USERPROFILE%\.pi\agent\settings.json point to a valid bash.exe
4. If Python-based features fail, verify that Python is installed and that `py -3 -c "import mempalace, mempalace.mcp_server"` works
5. If global editor integration is missing, inspect %USERPROFILE%\.pi\agent\settings.json and %USERPROFILE%\.pi\agents\AGENTS.md

Installed packages
------------------

- pi-subagents
- pi-mcp-adapter
- pi-lens
- pi-web-access
- mempalace-pi
'@
    $readme = $readme.Replace('__INSTALL_ROOT__', $ResolvedInstallRoot)
    Set-Content -LiteralPath $ReadmePath -Value $readme -Encoding UTF8

    Write-Step 'Validating package paths'
    foreach ($packagePath in $packagePaths) {
        $resolvedPath = Resolve-Path -LiteralPath (Join-Path $PiDir $packagePath) -ErrorAction Stop
        Write-Info "Install-root OK: $resolvedPath"
    }
    foreach ($packagePath in $globalPackagePaths) {
        $resolvedPath = Resolve-Path -LiteralPath $packagePath -ErrorAction Stop
        Write-Info "Global OK: $resolvedPath"
    }

    Write-Step 'Writing global AGENTS.md'
    $agentsMdContent = Get-AgentsMdContent -IncludeTwinCATAds:$IncludeTwinCATAds
    Set-GeneratedAgentsSection -Path $GlobalAgentsPath -GeneratedContent $agentsMdContent
    Write-Info "Global AGENTS.md: $GlobalAgentsPath"

    Write-Step 'Done'
    Write-Host 'Global installation prepared successfully.' -ForegroundColor Green
    Write-Host "Install root: $ResolvedInstallRoot"
    Write-Host "Global Pi settings: $GlobalPiAgentSettingsPath"
    Write-Host "Global AGENTS.md: $GlobalAgentsPath"
    Write-Host "Log file: $InstallLogPath"
    Write-Host ''
    Write-Host 'Start with:'
    Write-Host "  powershell -ExecutionPolicy Bypass -File `"$StartScriptPath`""
    Write-Host 'Or start pi from another repo/editor; the global Pi settings were updated as well.'
}
catch {
    $ScriptExitCode = 1
    Write-ErrorLine $_.Exception.Message
    if ($ResolvedInstallRoot) {
        Write-Host "Install root: $ResolvedInstallRoot" -ForegroundColor Yellow
    }
}
finally {
    if ($TranscriptStarted) {
        try { Stop-Transcript | Out-Null } catch {}
    }
}

exit $ScriptExitCode
