[CmdletBinding()]
param(
    [string]$InstallRoot = '',
    [switch]$IncludeTwinCATAds,
    [string]$TwinCATAdsSource,
    [string]$AgentVersion = '0.67.68',
    [switch]$RequirePython,
    [switch]$UseLatestPackageVersions,
    [switch]$UpdatePrerequisites
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$IsWindowsPlatform = if (Get-Variable -Name 'IsWindows' -ErrorAction SilentlyContinue) {
    [bool]$IsWindows
}
else {
    ($PSVersionTable.PSEdition -eq 'Desktop') -or ([Environment]::OSVersion.Platform -eq [PlatformID]::Win32NT)
}

$TranscriptStarted = $false
$ScriptExitCode = 0
$ResolvedInstallRoot = $null
$GlobalScriptPath = if ($MyInvocation.MyCommand.Path) { $MyInvocation.MyCommand.Path } else { $PSCommandPath }
$UserProfilePath = [Environment]::GetFolderPath('UserProfile')
$PreferredGlobalInstallRoot = Join-Path $UserProfilePath '.pi\stack'
$LegacyGlobalInstallRoot = Join-Path $UserProfilePath '.pi-stack'
$GlobalPiAgentDir = Join-Path $UserProfilePath '.pi\agent'
$GlobalPiAgentBinDir = Join-Path $GlobalPiAgentDir 'bin'
$GlobalPiAgentSettingsPath = Join-Path $GlobalPiAgentDir 'settings.json'
$GlobalPiAgentAuthPath = Join-Path $GlobalPiAgentDir 'auth.json'
$GlobalPiAgentBackupsDir = Join-Path $GlobalPiAgentDir 'backups'
$PiLensToolsDir = Join-Path $UserProfilePath '.pi-lens\tools'
$GlobalAgentsPath = Join-Path $GlobalPiAgentDir 'AGENTS.md'
$LegacyGlobalAgentsDir = Join-Path $UserProfilePath '.pi\agents'
$LegacyGlobalAgentsPath = Join-Path $LegacyGlobalAgentsDir 'AGENTS.md'

$PackageNames = @(
    'mempalace-pi',
    'pi-lens',
    'pi-mcp-adapter',
    'pi-subagents',
    'pi-web-access'
)

function Write-Step {
    param([Parameter(Mandatory = $true)][string]$Message)
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

function Write-Info {
    param([Parameter(Mandatory = $true)][string]$Message)
    Write-Host "[info] $Message" -ForegroundColor DarkGray
}

function Write-ErrorLine {
    param([Parameter(Mandatory = $true)][string]$Message)
    Write-Host "[error] $Message" -ForegroundColor Red
}

function Ensure-Directory {
    param([Parameter(Mandatory = $true)][string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

function Resolve-DefaultGlobalInstallRoot {
    param([string]$RequestedPath)

    if (-not [string]::IsNullOrWhiteSpace($RequestedPath)) {
        return $RequestedPath
    }

    if (Test-Path -LiteralPath $PreferredGlobalInstallRoot) {
        return $PreferredGlobalInstallRoot
    }

    if (Test-Path -LiteralPath $LegacyGlobalInstallRoot) {
        Write-Warning "Using legacy global install root '$LegacyGlobalInstallRoot'. Pass -InstallRoot explicitly if you want to migrate to '$PreferredGlobalInstallRoot'."
        return $LegacyGlobalInstallRoot
    }

    return $PreferredGlobalInstallRoot
}

function Set-GeneratedAgentsSection {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$GeneratedContent
    )

    $beginMarker = '<!-- BEGIN PI-SETUP-AUTOGENERATED -->'
    $endMarker = '<!-- END PI-SETUP-AUTOGENERATED -->'
    $block = $beginMarker + "`r`n" + $GeneratedContent.Trim() + "`r`n" + $endMarker + "`r`n"

    $existing = ''
    if (Test-Path -LiteralPath $Path) {
        $existing = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    }

    if ($existing -match [regex]::Escape($beginMarker) + '[\s\S]*?' + [regex]::Escape($endMarker)) {
        $updated = [regex]::Replace($existing, [regex]::Escape($beginMarker) + '[\s\S]*?' + [regex]::Escape($endMarker), $block.TrimEnd())
        Set-Content -LiteralPath $Path -Value ($updated.TrimEnd() + "`r`n") -Encoding UTF8
        return
    }

    $prefix = @"
# AGENTS.md

This file contains instructions for coding agents working with this Pi installation.

"@

    if ([string]::IsNullOrWhiteSpace($existing)) {
        Set-Content -LiteralPath $Path -Value ($prefix + $block) -Encoding UTF8
    }
    else {
        $separator = if ($existing.EndsWith("`n")) { "" } else { "`r`n" }
        Set-Content -LiteralPath $Path -Value ($existing + $separator + "`r`n" + $block) -Encoding UTF8
    }
}

function Remove-LegacyGlobalAgentsPath {
    if (Test-Path -LiteralPath $LegacyGlobalAgentsPath) {
        try {
            Remove-Item -LiteralPath $LegacyGlobalAgentsPath -Force -ErrorAction Stop
            Write-Info "Removed legacy global AGENTS.md: $LegacyGlobalAgentsPath"
        }
        catch {
            Write-Warning "Could not remove legacy global AGENTS.md '$LegacyGlobalAgentsPath': $($_.Exception.Message)"
        }
    }

    if (Test-Path -LiteralPath $LegacyGlobalAgentsDir) {
        try {
            $remainingEntries = @(Get-ChildItem -LiteralPath $LegacyGlobalAgentsDir -Force -ErrorAction Stop)
            if ($remainingEntries.Count -eq 0) {
                Remove-Item -LiteralPath $LegacyGlobalAgentsDir -Force -ErrorAction Stop
                Write-Info "Removed empty legacy global agents directory: $LegacyGlobalAgentsDir"
            }
        }
        catch {
            Write-Warning "Could not clean legacy global agents directory '$LegacyGlobalAgentsDir': $($_.Exception.Message)"
        }
    }
}

function Migrate-LegacyGlobalInstallLayout {
    param([Parameter(Mandatory = $true)][string]$InstallRootPath)

    $legacyPiDir = Join-Path $InstallRootPath '.pi'
    if (-not (Test-Path -LiteralPath $legacyPiDir)) {
        return
    }

    $moves = @(
        @{ Source = (Join-Path $legacyPiDir 'settings.json'); Destination = (Join-Path $InstallRootPath 'settings.json') },
        @{ Source = (Join-Path $legacyPiDir 'logs'); Destination = (Join-Path $InstallRootPath 'logs') },
        @{ Source = (Join-Path $legacyPiDir 'backups'); Destination = (Join-Path $InstallRootPath 'backups') }
    )

    foreach ($move in $moves) {
        if ((Test-Path -LiteralPath $move.Source) -and -not (Test-Path -LiteralPath $move.Destination)) {
            try {
                Move-Item -LiteralPath $move.Source -Destination $move.Destination -Force -ErrorAction Stop
                Write-Info "Migrated legacy global stack path: $($move.Source) -> $($move.Destination)"
            }
            catch {
                Write-Warning "Could not migrate legacy global stack path '$($move.Source)': $($_.Exception.Message)"
            }
        }
    }

    try {
        $remainingEntries = @(Get-ChildItem -LiteralPath $legacyPiDir -Force -ErrorAction Stop)
        if ($remainingEntries.Count -eq 0) {
            Remove-Item -LiteralPath $legacyPiDir -Force -ErrorAction Stop
            Write-Info "Removed empty legacy nested stack directory: $legacyPiDir"
        }
    }
    catch {
        Write-Warning "Could not clean legacy nested stack directory '$legacyPiDir': $($_.Exception.Message)"
    }
}

function Remove-UnwantedGlobalProjectArtifacts {
    param([Parameter(Mandatory = $true)][string]$InstallRootPath)

    $artifactPaths = @(
        (Join-Path $InstallRootPath '.pi'),
        (Join-Path $InstallRootPath '.pi-lens'),
        (Join-Path $InstallRootPath 'settings.json')
    )

    foreach ($artifactPath in $artifactPaths) {
        if (-not (Test-Path -LiteralPath $artifactPath)) {
            continue
        }

        try {
            Remove-Item -LiteralPath $artifactPath -Recurse -Force -ErrorAction Stop
            Write-Info "Removed stack-local project artifact: $artifactPath"
        }
        catch {
            Write-Warning "Could not remove stack-local project artifact '$artifactPath': $($_.Exception.Message)"
        }
    }
}

function Get-AgentsMdContent {
    $twincatSection = if ($IncludeTwinCATAds -or -not [string]::IsNullOrWhiteSpace($TwinCATAdsSource)) { @"
- `pi-twincat-ads`: Use for TwinCAT ADS communication and related automation tasks when the project requires it.
"@ } else { "" }

    return @"
## Pi setup tools available globally

Installed Pi packages:
- `pi-lens`: Prefer this for code understanding, LSP navigation, references, definitions, hover info, AST-aware search, and precise code changes.
- `mempalace-pi`: Treat this as a core part of the workflow. Use it actively for memory workflows, persistent project knowledge, reminders, decisions, follow-ups, and important discoveries that should survive the current session.
- `pi-subagents`: Use subagents when a task benefits from decomposition, parallel exploration, or specialized analysis.
- `pi-mcp-adapter`: Use MCP servers/tools when project tasks require external integrations or structured tool access.
- `pi-web-access`: Use web search/fetch only for external documentation or information not available in the repository.
$twincatSection
## Agent usage guidance

- Start with local repository context first, but assume these globally installed Pi tools may be available across repositories and editors.
- Use `mempalace-pi` as an active workflow component, not just as optional storage.
- When you learn something likely to matter later, store it in `mempalace-pi`.
- Before or during complex work, consider whether relevant prior knowledge from `mempalace-pi` may exist.
- Prefer `pi-lens`/LSP and AST-aware search over plain text search when navigating or modifying code.
- Use `pi-subagents` only when the task is complex enough to benefit from delegation.
- Use `pi-mcp-adapter` and `pi-web-access` deliberately, not by default.
- Keep edits minimal, precise, and consistent with each repository's existing structure.
- When changing behavior, also update nearby documentation and scripts if needed.
- For Python-backed features such as `mempalace-pi` on Windows, prefer the provided start scripts and UTF-8 environment settings.

## Global project note

This `AGENTS.md` section was generated by `scripts/install-pi-stack-global.ps1`.
You may add custom instructions outside the autogenerated block.
"@
}

function Refresh-ProcessPath {
    $machinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    $combined = @($machinePath, $userPath) -join ';'
    if (-not [string]::IsNullOrWhiteSpace($combined)) {
        $env:Path = $combined
    }
}

function Get-CommandPathSafe {
    param([Parameter(Mandatory = $true)][string]$Name)
    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    return $null
}

function Test-MapHasKey {
    param(
        [Parameter(Mandatory = $true)]$Map,
        [Parameter(Mandatory = $true)][string]$Key
    )

    if ($null -eq $Map) { return $false }
    if ($Map -is [System.Collections.IDictionary]) { return $Map.Contains($Key) }

    $property = $Map.PSObject.Properties[$Key]
    return $null -ne $property
}

function Test-CommandExists {
    param([Parameter(Mandatory = $true)][string]$Name)
    return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Invoke-External {
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [string[]]$Arguments = @(),
        [string]$WorkingDirectory,
        [int[]]$AcceptableExitCodes = @()
    )

    if ($WorkingDirectory) { Push-Location $WorkingDirectory }
    $prevEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        Write-Info ("Run: " + $FilePath + ' ' + ($Arguments -join ' '))
        & $FilePath @Arguments
        $exitCode = $LASTEXITCODE
        if ($exitCode -ne 0 -and $AcceptableExitCodes -notcontains $exitCode) {
            throw "Command failed ($exitCode): $FilePath $($Arguments -join ' ')"
        }
    }
    finally {
        $ErrorActionPreference = $prevEap
        if ($WorkingDirectory) { Pop-Location }
    }
}

function Invoke-WithRetry {
    param(
        [Parameter(Mandatory = $true)][scriptblock]$Action,
        [Parameter(Mandatory = $true)][string]$Description,
        [int]$MaxAttempts = 3,
        [int]$DelaySeconds = 4
    )

    $attempt = 0
    while ($attempt -lt $MaxAttempts) {
        $attempt++
        try {
            Write-Info "$Description (attempt $attempt/$MaxAttempts)"
            & $Action
            return
        }
        catch {
            if ($attempt -ge $MaxAttempts) { throw }
            Write-Warning "$Description failed: $($_.Exception.Message)"
            Write-Info "Waiting $DelaySeconds seconds before the next attempt ..."
            Start-Sleep -Seconds $DelaySeconds
        }
    }
}

function Get-PythonCommandSpec {
    param([Parameter(Mandatory = $true)][string]$PythonPath)

    $leaf = Split-Path -Leaf $PythonPath
    $baseArguments = @()
    if ($leaf -ieq 'py.exe' -or $leaf -ieq 'py') {
        $baseArguments += '-3'
    }

    return [ordered]@{
        FilePath      = $PythonPath
        BaseArguments = $baseArguments
    }
}

function Invoke-PythonCommand {
    param(
        [Parameter(Mandatory = $true)][string]$PythonPath,
        [Parameter(Mandatory = $true)][string[]]$Arguments,
        [string]$WorkingDirectory
    )

    $pythonSpec = Get-PythonCommandSpec -PythonPath $PythonPath
    $allArguments = @($pythonSpec['BaseArguments']) + @($Arguments)
    Invoke-External -FilePath $pythonSpec['FilePath'] -Arguments $allArguments -WorkingDirectory $WorkingDirectory
}

function Install-MemPalacePythonBackend {
    param([Parameter(Mandatory = $true)][string]$PythonPath)

    $env:PYTHONUTF8 = '1'
    $env:PYTHONIOENCODING = 'utf-8'

    Write-Step 'Installing MemPalace Python backend'
    Invoke-WithRetry -Description 'python -m pip install --upgrade mempalace' -Action {
        Invoke-PythonCommand -PythonPath $PythonPath -Arguments @('-m', 'pip', 'install', '--upgrade', 'mempalace')
    } -MaxAttempts 3 -DelaySeconds 5

    Write-Step 'Validating MemPalace Python backend'
    Invoke-PythonCommand -PythonPath $PythonPath -Arguments @('-c', 'import mempalace; import mempalace.mcp_server')
}

function Write-Python3Shim {
    param([Parameter(Mandatory = $true)][string]$Path)

    $shimContent = @"
@echo off
setlocal
where py >nul 2>nul
if not errorlevel 1 (
    py -3 %*
    exit /b %ERRORLEVEL%
)
where python >nul 2>nul
if not errorlevel 1 (
    python %*
    exit /b %ERRORLEVEL%
)
echo python3 shim could not find py or python on PATH. 1>&2
exit /b 9009
"@

    Ensure-Directory -Path (Split-Path -Parent $Path)
    Set-Content -LiteralPath $Path -Value ($shimContent.Trim() + "`r`n") -Encoding ASCII
}

function Install-PiLensCliTools {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    Ensure-Directory -Path $PiLensToolsDir

    $packageJsonPath = Join-Path $PiLensToolsDir 'package.json'
    if (-not (Test-Path -LiteralPath $packageJsonPath)) {
        $packageJson = [ordered]@{
            name    = 'pi-lens-tools'
            private = $true
        }
        Save-JsonObject -Path $packageJsonPath -Data $packageJson
    }

    $tools = @(
        @{ Package = '@ast-grep/cli'; Binary = 'sg.cmd'; VerifyArgs = @('--version') },
        @{ Package = 'knip'; Binary = 'knip.cmd'; VerifyArgs = @('--version') },
        @{ Package = 'jscpd'; Binary = 'jscpd.cmd'; VerifyArgs = @('--version') },
        @{ Package = 'madge'; Binary = 'madge.cmd'; VerifyArgs = @('--version') }
    )

    foreach ($tool in $tools) {
        Invoke-WithRetry -Description ("npm install {0} for pi-lens" -f $tool.Package) -Action {
            Invoke-External -FilePath $NpmExe -WorkingDirectory $PiLensToolsDir -Arguments @('install', '--no-audit', '--no-fund', $tool.Package)
        } -MaxAttempts 2 -DelaySeconds 5

        $binaryPath = Join-Path $PiLensToolsDir ("node_modules\.bin\" + $tool.Binary)
        if (-not (Test-Path -LiteralPath $binaryPath)) {
            throw "pi-lens tool install did not produce expected binary: $binaryPath"
        }

        Invoke-External -FilePath $binaryPath -WorkingDirectory $PiLensToolsDir -Arguments $tool.VerifyArgs
    }
}

function Repair-PiLensTooling {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    Write-Step 'Preparing pi-lens tooling on Windows'

    Ensure-Command -Name 'rg' -WingetPackageId 'BurntSushi.ripgrep.MSVC' -DisplayName 'ripgrep (rg)' -Optional | Out-Null
    Ensure-Command -Name 'fd' -WingetPackageId 'sharkdp.fd' -DisplayName 'fd' -Optional | Out-Null

    if (Test-Path -LiteralPath $PiLensToolsDir) {
        try {
            Remove-Item -LiteralPath $PiLensToolsDir -Recurse -Force -ErrorAction Stop
            Write-Info "Removed stale pi-lens tools cache: $PiLensToolsDir"
        }
        catch {
            Write-Warning "Could not reset pi-lens tools cache '$PiLensToolsDir': $($_.Exception.Message)"
        }
    }

    try {
        Install-PiLensCliTools -NpmExe $NpmExe
    }
    catch {
        Write-Warning "Could not fully preinstall pi-lens CLI tools: $($_.Exception.Message)"
    }
}

function Get-NpmViewText {
    param(
        [Parameter(Mandatory = $true)][string]$NpmExe,
        [Parameter(Mandatory = $true)][string[]]$Arguments
    )

    $output = & $NpmExe @Arguments 2>$null
    if ($LASTEXITCODE -ne 0) {
        return $null
    }

    $text = ($output | Out-String).Trim()
    if ([string]::IsNullOrWhiteSpace($text)) {
        return $null
    }

    return $text
}

function Get-NpmViewJson {
    param(
        [Parameter(Mandatory = $true)][string]$NpmExe,
        [Parameter(Mandatory = $true)][string[]]$Arguments
    )

    $text = Get-NpmViewText -NpmExe $NpmExe -Arguments $Arguments
    if ([string]::IsNullOrWhiteSpace($text)) {
        return $null
    }

    try {
        return ($text | ConvertFrom-Json)
    }
    catch {
        return $null
    }
}

function Test-NpmPackageVersionExists {
    param(
        [Parameter(Mandatory = $true)][string]$NpmExe,
        [Parameter(Mandatory = $true)][string]$PackageName,
        [Parameter(Mandatory = $true)][string]$Version
    )

    $result = & $NpmExe 'view' ("$PackageName@$Version") 'version' '--json' 2>$null
    if ($LASTEXITCODE -ne 0) {
        return $false
    }

    $text = ($result | Out-String).Trim().Trim('"')
    return $text -eq $Version
}

function Get-GlobalNpmRoot {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    $text = Get-NpmViewText -NpmExe $NpmExe -Arguments @('root', '-g')
    if ([string]::IsNullOrWhiteSpace($text)) {
        return $null
    }

    return $text.Split([Environment]::NewLine)[0].Trim()
}

function Get-GlobalPiCodingAgentPath {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    $globalRoot = Get-GlobalNpmRoot -NpmExe $NpmExe
    if ([string]::IsNullOrWhiteSpace($globalRoot)) {
        return $null
    }

    return (Join-Path $globalRoot '@mariozechner\pi-coding-agent')
}

function Get-PiRelatedRunningProcesses {
    $results = @()
    try {
        $processes = Get-CimInstance Win32_Process -ErrorAction Stop | Where-Object {
            $_.Name -match '^(node|npm|powershell|pwsh|cmd|bash)(\.exe)?$'
        }

        foreach ($process in $processes) {
            $commandLine = [string]$process.CommandLine
            if ($commandLine -match 'pi-coding-agent|\\npm\\pi\.(cmd|ps1)\b') {
                $results += [PSCustomObject]@{
                    ProcessId   = $process.ProcessId
                    Name        = $process.Name
                    CommandLine = $commandLine
                }
            }
        }
    }
    catch {
        Write-Warning "Could not inspect running processes: $($_.Exception.Message)"
    }

    return @($results)
}

function Warn-AboutPiRelatedProcesses {
    $processes = @(Get-PiRelatedRunningProcesses)
    if ($processes.Count -eq 0) {
        return
    }

    Write-Warning 'Detected running pi/npm/node-related processes. On Windows these can lock files and cause npm EPERM cleanup/install issues.'
    foreach ($process in $processes | Select-Object -First 5) {
        Write-Warning ("PID {0} {1}: {2}" -f $process.ProcessId, $process.Name, $process.CommandLine)
    }
    if ($processes.Count -gt 5) {
        Write-Warning ("... and {0} more process(es)." -f ($processes.Count - 5))
    }
}

function Remove-StaleGlobalPiCodingAgent {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    $packagePath = Get-GlobalPiCodingAgentPath -NpmExe $NpmExe
    $appData = [Environment]::GetFolderPath('ApplicationData')
    $shimCandidates = @(
        (Join-Path $appData 'npm\pi.cmd'),
        (Join-Path $appData 'npm\pi'),
        (Join-Path $appData 'npm\node_modules\@mariozechner\pi-coding-agent')
    )

    Warn-AboutPiRelatedProcesses

    try {
        Invoke-External -FilePath $NpmExe -Arguments @('uninstall', '-g', '@mariozechner/pi-coding-agent', '--no-fund', '--no-audit')
    }
    catch {
        Write-Warning "Global uninstall reported an issue: $($_.Exception.Message)"
    }

    foreach ($candidate in @($packagePath) + $shimCandidates) {
        if (-not [string]::IsNullOrWhiteSpace($candidate) -and (Test-Path -LiteralPath $candidate)) {
            try {
                Remove-Item -LiteralPath $candidate -Recurse -Force -ErrorAction Stop
                Write-Info "Removed stale path: $candidate"
            }
            catch {
                Write-Warning "Could not remove stale path '$candidate': $($_.Exception.Message)"
            }
        }
    }
}

function Install-GlobalPiCodingAgent {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    $packageSpecifier = '@mariozechner/pi-coding-agent'
    if (-not [string]::IsNullOrWhiteSpace($AgentVersion)) {
        if (-not (Test-NpmPackageVersionExists -NpmExe $NpmExe -PackageName '@mariozechner/pi-coding-agent' -Version $AgentVersion)) {
            throw "Requested version @mariozechner/pi-coding-agent@$AgentVersion is not available on npm."
        }
        $packageSpecifier = "@mariozechner/pi-coding-agent@$AgentVersion"
    }

    $versionJson = Get-NpmViewJson -NpmExe $NpmExe -Arguments @('view', '@mariozechner/pi-coding-agent', 'version', '--json')
    $latestInfo = if ($versionJson) { ($versionJson | Out-String).Trim() } else { 'unknown' }
    Write-Info "Installing $packageSpecifier (npm latest currently: $latestInfo)"

    Invoke-WithRetry -Description 'npm uninstall/install -g @mariozechner/pi-coding-agent' -Action {
        Remove-StaleGlobalPiCodingAgent -NpmExe $NpmExe
        Invoke-External -FilePath $NpmExe -Arguments @('install', '-g', $packageSpecifier, '--no-fund', '--no-audit')
    } -MaxAttempts 3 -DelaySeconds 5
}

function Invoke-WingetProcess {
    param(
        [Parameter(Mandatory = $true)][string]$WingetPath,
        [Parameter(Mandatory = $true)][string[]]$Arguments,
        [int[]]$AcceptableExitCodes = @()
    )

    Write-Info ("Run: " + $WingetPath + ' ' + ($Arguments -join ' '))
    $process = Start-Process -FilePath $WingetPath -ArgumentList $Arguments -Wait -NoNewWindow -PassThru
    $exitCode = $process.ExitCode
    if ($exitCode -ne 0 -and $AcceptableExitCodes -notcontains $exitCode) {
        throw "Command failed ($exitCode): $WingetPath $($Arguments -join ' ')"
    }
}

function Invoke-WingetInstall {
    param(
        [Parameter(Mandatory = $true)][string]$PackageId,
        [Parameter(Mandatory = $true)][string]$DisplayName
    )

    $winget = Get-CommandPathSafe -Name 'winget'
    if (-not $winget) {
        throw "'$DisplayName' is missing and winget is not available. Please install it manually."
    }

    Write-Step "Installing $DisplayName via winget"
    Invoke-WithRetry -Description "winget install $PackageId" -Action {
        Invoke-WingetProcess -WingetPath $winget -Arguments @(
            'install', '--id', $PackageId, '--exact', '--silent',
            '--accept-package-agreements', '--accept-source-agreements', '--disable-interactivity'
        )
    } -MaxAttempts 2 -DelaySeconds 5
    Refresh-ProcessPath
}

function Invoke-WingetUpgrade {
    param(
        [Parameter(Mandatory = $true)][string]$PackageId,
        [Parameter(Mandatory = $true)][string]$DisplayName
    )

    $winget = Get-CommandPathSafe -Name 'winget'
    if (-not $winget) {
        Write-Warning "winget is not available, so '$DisplayName' could not be checked for updates."
        return
    }

    # 0x8A15002B = WINGET_NO_APPLICABLE_UPGRADE (already up to date)
    $noUpgradeExitCode = -1978335189

    Write-Step "Checking for updates for $DisplayName via winget"
    try {
        Invoke-WithRetry -Description "winget upgrade $PackageId" -Action {
            Invoke-WingetProcess -WingetPath $winget -Arguments @(
                'upgrade', '--id', $PackageId, '--exact', '--silent',
                '--accept-package-agreements', '--accept-source-agreements', '--disable-interactivity',
                '--include-unknown'
            ) -AcceptableExitCodes @($noUpgradeExitCode)
        } -MaxAttempts 2 -DelaySeconds 5
        Refresh-ProcessPath
    }
    catch {
        Write-Warning "Could not update '$DisplayName' via winget: $($_.Exception.Message)"
    }
}

function Ensure-Command {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [string]$WingetPackageId,
        [string]$DisplayName = $Name,
        [switch]$Optional
    )

    if (Test-CommandExists -Name $Name) {
        if ($WingetPackageId -and $UpdatePrerequisites) {
            Invoke-WingetUpgrade -PackageId $WingetPackageId -DisplayName $DisplayName
        }
        return (Get-CommandPathSafe -Name $Name)
    }

    if ($WingetPackageId) {
        try {
            Invoke-WingetInstall -PackageId $WingetPackageId -DisplayName $DisplayName
        }
        catch {
            if ($Optional) {
                Write-Warning $_.Exception.Message
                return $null
            }
            throw
        }

        if (Test-CommandExists -Name $Name) {
            return (Get-CommandPathSafe -Name $Name)
        }
    }

    if ($Optional) {
        Write-Warning "'$DisplayName' was not found."
        return $null
    }

    throw "'$DisplayName' was not found."
}

function Save-JsonObject {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)]$Data
    )

    Ensure-Directory -Path (Split-Path -Parent $Path)
    $json = $Data | ConvertTo-Json -Depth 100
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, ($json + "`n"), $utf8NoBom)
}

function ConvertTo-HashtableCompatible {
    param($InputObject)

    if ($null -eq $InputObject) {
        return $null
    }

    if ($InputObject -is [System.Collections.IDictionary]) {
        $result = [ordered]@{}
        foreach ($key in $InputObject.Keys) {
            $result[$key] = ConvertTo-HashtableCompatible -InputObject $InputObject[$key]
        }
        return $result
    }

    if (($InputObject -is [System.Collections.IEnumerable]) -and ($InputObject -isnot [string])) {
        $result = @()
        foreach ($item in $InputObject) {
            $result += ,(ConvertTo-HashtableCompatible -InputObject $item)
        }
        return $result
    }

    if ($InputObject -is [psobject]) {
        $properties = @($InputObject.PSObject.Properties | Where-Object { $_.MemberType -like '*Property' })
        if ($properties.Count -gt 0) {
            $result = [ordered]@{}
            foreach ($property in $properties) {
                $result[$property.Name] = ConvertTo-HashtableCompatible -InputObject $property.Value
            }
            return $result
        }
    }

    return $InputObject
}

function Load-JsonObject {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        return [ordered]@{}
    }

    $raw = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    if ([string]::IsNullOrWhiteSpace($raw)) {
        return [ordered]@{}
    }

    try {
        $convertFromJsonCommand = Get-Command ConvertFrom-Json -ErrorAction Stop
        if ($convertFromJsonCommand.Parameters.ContainsKey('AsHashtable')) {
            $parsed = $raw | ConvertFrom-Json -AsHashtable
        }
        else {
            $parsed = ConvertTo-HashtableCompatible -InputObject ($raw | ConvertFrom-Json)
        }

        if ($null -eq $parsed) {
            return [ordered]@{}
        }
        return $parsed
    }
    catch {
        throw "Could not parse JSON file '$Path': $($_.Exception.Message)"
    }
}

function Merge-UniqueStrings {
    param(
        $Existing,
        [string[]]$Incoming
    )

    $seen = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
    $result = New-Object System.Collections.Generic.List[string]

    foreach ($item in @($Existing) + @($Incoming)) {
        if ($item -isnot [string]) { continue }
        if ([string]::IsNullOrWhiteSpace($item)) { continue }
        if ($seen.Add($item)) {
            [void]$result.Add($item)
        }
    }

    return @($result)
}

function Get-NpmExecutable {
    $npmCmd = Get-CommandPathSafe -Name 'npm.cmd'
    if ($npmCmd) { return $npmCmd }
    $npm = Get-CommandPathSafe -Name 'npm'
    if ($npm) { return $npm }
    return $null
}

function Get-PiExecutable {
    param([string]$NpmExe)

    if ($NpmExe) {
        $globalRoot = Get-GlobalNpmRoot -NpmExe $NpmExe
        if (-not [string]::IsNullOrWhiteSpace($globalRoot)) {
            $globalBin = Split-Path -Parent $globalRoot
            if (-not [string]::IsNullOrWhiteSpace($globalBin)) {
                $piCmd = Join-Path $globalBin 'pi.cmd'
                if (Test-Path -LiteralPath $piCmd) {
                    return $piCmd
                }
            }
        }
    }

    $appData = [Environment]::GetFolderPath('ApplicationData')
    $fallbackPiCmd = Join-Path $appData 'npm\pi.cmd'
    if (Test-Path -LiteralPath $fallbackPiCmd) {
        return $fallbackPiCmd
    }

    $piCmdResolved = Get-CommandPathSafe -Name 'pi.cmd'
    if ($piCmdResolved) { return $piCmdResolved }

    $pi = Get-CommandPathSafe -Name 'pi'
    if ($pi) { return $pi }

    return $null
}

function Get-GitBashPath {
    $candidates = New-Object System.Collections.Generic.List[string]

    foreach ($baseDir in @($env:ProgramFiles, ${env:ProgramFiles(x86)})) {
        if ([string]::IsNullOrWhiteSpace($baseDir)) { continue }
        $candidates.Add((Join-Path $baseDir 'Git\bin\bash.exe'))
    }

    $gitPath = Get-CommandPathSafe -Name 'git'
    if ($gitPath) {
        $gitCmdDir = Split-Path -Parent $gitPath
        $gitRootDir = Split-Path -Parent $gitCmdDir
        if (-not [string]::IsNullOrWhiteSpace($gitRootDir)) {
            $candidates.Add((Join-Path $gitRootDir 'bin\bash.exe'))
        }
    }

    foreach ($candidate in $candidates) {
        if (Test-Path -LiteralPath $candidate) {
            return $candidate
        }
    }

    $bash = Get-CommandPathSafe -Name 'bash'
    if ($bash) { return $bash }
    return $null
}

function Get-PowerShellExecutablePath {
    $currentShellPath = Get-CommandPathSafe -Name 'powershell'
    if ($currentShellPath) {
        return $currentShellPath
    }

    $systemRoot = [Environment]::GetEnvironmentVariable('SystemRoot')
    if (-not [string]::IsNullOrWhiteSpace($systemRoot)) {
        $fallback = Join-Path $systemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
        if (Test-Path -LiteralPath $fallback) {
            return $fallback
        }
    }

    return 'powershell.exe'
}

function Get-PiPackageSources {
    $sources = @()
    foreach ($name in $PackageNames) {
        $sources += ("npm:{0}" -f $name)
    }
    return $sources
}

function Test-PiAuthenticated {
    if (-not (Test-Path -LiteralPath $GlobalPiAgentAuthPath)) {
        return $false
    }

    try {
        $raw = Get-Content -LiteralPath $GlobalPiAgentAuthPath -Raw -Encoding UTF8
        return -not [string]::IsNullOrWhiteSpace($raw)
    }
    catch {
        Write-Warning "Could not inspect Pi auth state at '$GlobalPiAgentAuthPath': $($_.Exception.Message)"
        return $false
    }
}

function Start-PiLoginIfNeeded {
    param(
        [Parameter(Mandatory = $true)][string]$PiExecutablePath,
        [Parameter(Mandatory = $true)][string]$WorkingDirectory,
        [Parameter(Mandatory = $true)][string]$StartScriptPath
    )

    if (Test-PiAuthenticated) {
        Write-Info 'Pi authentication already present. Skipping automatic login.'
        return
    }

    Write-Step 'Pi authentication required'
    Write-Warning 'No existing Pi authentication was found.'
    Write-Host 'Pi does not provide a non-interactive login flag for this flow.' -ForegroundColor Yellow
    Write-Host 'Start Pi and then run /login inside the Pi prompt.' -ForegroundColor Yellow
    Write-Host ''
    Write-Host 'Recommended command:' -ForegroundColor Yellow
    Write-Host ("  powershell -ExecutionPolicy Bypass -File `"{0}`"" -f $StartScriptPath) -ForegroundColor Yellow
    Write-Host 'Then type: /login' -ForegroundColor Yellow

    if (Test-Path -LiteralPath $StartScriptPath) {
        Write-Info 'Opening a new PowerShell window for Pi login.'
        try {
            Start-Process -FilePath (Get-PowerShellExecutablePath) -ArgumentList @(
                '-NoExit',
                '-ExecutionPolicy',
                'Bypass',
                '-File',
                $StartScriptPath
            ) | Out-Null
        }
        catch {
            Write-Warning "Could not open a new PowerShell window automatically: $($_.Exception.Message)"
        }
    }
}

function Install-TwinCATAdsPackage {
    param([Parameter(Mandatory = $true)][string]$PiExecutablePath)

    $source = if ([string]::IsNullOrWhiteSpace($TwinCATAdsSource)) {
        'npm:pi-twincat-ads'
    }
    else {
        (Resolve-Path -LiteralPath $TwinCATAdsSource -ErrorAction Stop).Path
    }

    $description = if ([string]::IsNullOrWhiteSpace($TwinCATAdsSource)) {
        'pi install npm:pi-twincat-ads'
    }
    else {
        'pi install local pi-twincat-ads source'
    }

    $label = if ([string]::IsNullOrWhiteSpace($TwinCATAdsSource)) {
        'Installing pi-twincat-ads from npm'
    }
    else {
        'Installing pi-twincat-ads from local path'
    }

    Write-Step $label
    Invoke-WithRetry -Description $description -Action {
        Invoke-External -FilePath $PiExecutablePath -WorkingDirectory $UserProfilePath -Arguments @('install', $source)
    } -MaxAttempts 3 -DelaySeconds 5
}

function Install-PiPackages {
    param([Parameter(Mandatory = $true)][string]$PiExecutablePath)

    Write-Step 'Installing global Pi packages via pi install'
    foreach ($source in Get-PiPackageSources) {
        Invoke-WithRetry -Description ("pi install {0}" -f $source) -Action {
            Invoke-External -FilePath $PiExecutablePath -WorkingDirectory $UserProfilePath -Arguments @('install', $source)
        } -MaxAttempts 3 -DelaySeconds 5
    }
}

if (-not $IsWindowsPlatform) {
    throw 'This global script is intended for Windows.'
}

try {
    $InstallRoot = Resolve-DefaultGlobalInstallRoot -RequestedPath $InstallRoot
    Ensure-Directory -Path $InstallRoot
    $ResolvedInstallRoot = (Resolve-Path -LiteralPath $InstallRoot).Path
    Migrate-LegacyGlobalInstallLayout -InstallRootPath $ResolvedInstallRoot
    Remove-UnwantedGlobalProjectArtifacts -InstallRootPath $ResolvedInstallRoot

    $ScriptsDir = Join-Path $ResolvedInstallRoot 'scripts'
    $ShimDir = Join-Path $ResolvedInstallRoot 'bin'
    $PythonShimPath = Join-Path $ShimDir 'python3.cmd'
    $GlobalPythonShimPath = Join-Path $GlobalPiAgentBinDir 'python3.cmd'
    $LogsDir = Join-Path $ResolvedInstallRoot 'logs'
    $BackupsDir = Join-Path $ResolvedInstallRoot 'backups'
    $StartScriptPath = Join-Path $ScriptsDir 'start-pi.ps1'
    $ReadmePath = Join-Path $ResolvedInstallRoot 'README-global-pi-stack.txt'
    $InstallLogPath = Join-Path $LogsDir ("global-install-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.log')

    Ensure-Directory -Path $ScriptsDir
    Ensure-Directory -Path $ShimDir
    Ensure-Directory -Path $LogsDir
    Ensure-Directory -Path $BackupsDir
    Ensure-Directory -Path $GlobalPiAgentDir
    Ensure-Directory -Path $GlobalPiAgentBinDir
    Ensure-Directory -Path $GlobalPiAgentBackupsDir

    try {
        Start-Transcript -Path $InstallLogPath -Force | Out-Null
        $TranscriptStarted = $true
    }
    catch {
        Write-Warning "Could not start transcript: $($_.Exception.Message)"
    }

    Write-Info "Install target: $ResolvedInstallRoot"
    Write-Info "Global Pi settings: $GlobalPiAgentSettingsPath"
    Write-Info "Install log: $InstallLogPath"

    Write-Step 'Checking and installing prerequisites'
    $nodePath = Ensure-Command -Name 'node' -WingetPackageId 'OpenJS.NodeJS.LTS' -DisplayName 'Node.js LTS'
    $npmExe = Get-NpmExecutable
    if (-not $npmExe) {
        throw 'npm was not found after installing Node.js.'
    }
    $gitPath = Ensure-Command -Name 'git' -WingetPackageId 'Git.Git' -DisplayName 'Git for Windows'
    $gitBashPath = Get-GitBashPath
    if (-not $gitBashPath) {
        throw 'Git Bash (bash.exe) was not found after installing Git for Windows.'
    }

    if (-not [string]::IsNullOrWhiteSpace($TwinCATAdsSource) -and -not $IncludeTwinCATAds) {
        Write-Info 'TwinCATAdsSource was provided without IncludeTwinCATAds. Treating the source path as an implicit TwinCAT enable.'
    }

    $pythonPath = Get-CommandPathSafe -Name 'py'
    if (-not $pythonPath) {
        $pythonPath = Get-CommandPathSafe -Name 'python'
    }

    if (-not $pythonPath) {
        $pythonPath = Ensure-Command -Name 'py' -WingetPackageId 'Python.Python.3.12' -DisplayName 'Python Launcher' -Optional
        if (-not $pythonPath) {
            $pythonPath = Get-CommandPathSafe -Name 'python'
        }
        if (-not $pythonPath) {
            $pythonPath = Ensure-Command -Name 'python' -WingetPackageId 'Python.Python.3.12' -DisplayName 'Python 3'
        }
    }

    if (-not $pythonPath) {
        throw 'Python is required for mempalace-pi but could not be installed or found.'
    }

    Refresh-ProcessPath

    Write-Host "node: $(& $nodePath --version)"
    Write-Host "npm:  $(& $npmExe --version)"
    Write-Host "git:  $(& $gitPath --version)"
    Write-Host "bash: $gitBashPath"

    try {
        Write-Host "python: $(& $pythonPath --version 2>&1)"
    }
    catch {
        Write-Warning "Python was found, but its version could not be read: $($_.Exception.Message)"
    }

    Install-MemPalacePythonBackend -PythonPath $pythonPath
    Write-Step 'Writing python3 compatibility shim for Windows'
    Write-Python3Shim -Path $PythonShimPath
    Write-Python3Shim -Path $GlobalPythonShimPath
    Repair-PiLensTooling -NpmExe $npmExe

    Install-GlobalPiCodingAgent -NpmExe $npmExe
    Refresh-ProcessPath

    $piExe = Get-PiExecutable -NpmExe $npmExe
    if (-not $piExe) {
        throw 'pi was not found after the global npm install.'
    }
    Write-Host "pi:   $(& $piExe --version)"

    Install-PiPackages -PiExecutablePath $piExe
    if ($IncludeTwinCATAds -or -not [string]::IsNullOrWhiteSpace($TwinCATAdsSource)) {
        Install-TwinCATAdsPackage -PiExecutablePath $piExe
    }

    Write-Step 'Writing global Pi settings'
    if (Test-Path -LiteralPath $GlobalPiAgentSettingsPath) {
        $globalSettingsBackupPath = Join-Path $GlobalPiAgentBackupsDir ('settings-' + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.json.bak')
        Copy-Item -LiteralPath $GlobalPiAgentSettingsPath -Destination $globalSettingsBackupPath -Force
        Write-Info "Global Pi settings backup: $globalSettingsBackupPath"
    }

    $globalSettings = Load-JsonObject -Path $GlobalPiAgentSettingsPath
    $globalSettings['npmCommand'] = @('npm.cmd')
    $globalSettings['shellPath'] = $gitBashPath
    if (-not (Test-MapHasKey -Map $globalSettings -Key 'sessionDir') -or [string]::IsNullOrWhiteSpace([string]$globalSettings['sessionDir'])) {
        $globalSettings['sessionDir'] = '.pi/sessions'
    }
    Save-JsonObject -Path $GlobalPiAgentSettingsPath -Data $globalSettings

    Write-Step 'Writing start script'
    $startScript = @"
param(
    [Parameter(ValueFromRemainingArguments = `$true)]
    [string[]]`$PiArgs
)

`$ErrorActionPreference = 'Stop'
`$env:PYTHONUTF8 = '1'
`$env:PYTHONIOENCODING = 'utf-8'
`$ScriptDir = Split-Path -Parent `$MyInvocation.MyCommand.Path
`$InstallRoot = Split-Path -Parent `$ScriptDir
`$ShimDir = Join-Path `$InstallRoot 'bin'
`$GlobalAgentBinDir = Join-Path ([Environment]::GetFolderPath('UserProfile')) '.pi\agent\bin'
if (Test-Path -LiteralPath `$GlobalAgentBinDir) {
    `$env:Path = `$GlobalAgentBinDir + ';' + `$env:Path
}
if (Test-Path -LiteralPath `$ShimDir) {
    `$env:Path = `$ShimDir + ';' + `$env:Path
}

`$piCmd = Get-Command 'pi' -ErrorAction SilentlyContinue
`$piCmdPath = if (`$piCmd) { `$piCmd.Source } else { `$null }
if (-not `$piCmdPath) {
    `$piFallback = Join-Path ([Environment]::GetFolderPath('ApplicationData')) 'npm\pi.cmd'
    if (Test-Path -LiteralPath `$piFallback) {
        `$piCmdPath = `$piFallback
    }
}

if (-not `$piCmdPath) {
    throw 'pi was not found. Please run install-pi-stack-global.ps1 first.'
}

& `$piCmdPath @PiArgs
exit `$LASTEXITCODE
"@
    Set-Content -LiteralPath $StartScriptPath -Value $startScript -Encoding UTF8

    Write-Step 'Writing global install README'
    $readme = @'
Global Pi Setup Stack
=====================

This global Pi stack has been set up successfully.

Install root:
__INSTALL_ROOT__

What is included
----------------

- global @mariozechner/pi-coding-agent
- globally installed Pi packages via `pi install`
- global Pi settings in %USERPROFILE%\.pi\agent\settings.json
- global agent guidance in %USERPROFILE%\.pi\agent\AGENTS.md
- install-root Windows start script in scripts\start-pi.ps1
- install logs in logs\

Important files
---------------

- scripts\start-pi.ps1
- README-global-pi-stack.txt
- logs\
- %USERPROFILE%\.pi\agent\settings.json
- %USERPROFILE%\.pi\agent\AGENTS.md

Recommended usage
-----------------

To start Pi from this global install root:

powershell -ExecutionPolicy Bypass -File .\scripts\start-pi.ps1

You can also start Pi from other repos or editors that use the global Pi configuration.

Why use the start script?
-------------------------

The start script sets these environment variables for the current session:

- PYTHONUTF8=1
- PYTHONIOENCODING=utf-8

That is especially useful on Windows, in particular for mempalace-pi. The installer also provisions the Python `mempalace` backend so the MemPalace agent tools can run.

If something goes wrong
-----------------------

1. Check the latest file in logs\
2. Verify that pi, node, npm, and git are available
3. Confirm that Git Bash exists and that %USERPROFILE%\.pi\agent\settings.json points to a valid bash.exe
4. If Python-based features fail, verify that Python is installed and that `py -3 -c "import mempalace, mempalace.mcp_server"` works
5. If global editor integration is missing, inspect %USERPROFILE%\.pi\agent\settings.json and %USERPROFILE%\.pi\agent\AGENTS.md

Installed packages
------------------

- pi-subagents
- pi-mcp-adapter
- pi-lens
- pi-web-access
- mempalace-pi
'@
    if ($IncludeTwinCATAds -or -not [string]::IsNullOrWhiteSpace($TwinCATAdsSource)) {
        $readme += @'
- pi-twincat-ads
'@
    }
    $readme = $readme.Replace('__INSTALL_ROOT__', $ResolvedInstallRoot)
    Set-Content -LiteralPath $ReadmePath -Value $readme -Encoding UTF8

    Write-Step 'Writing global AGENTS.md'
    $agentsMdContent = Get-AgentsMdContent
    Set-GeneratedAgentsSection -Path $GlobalAgentsPath -GeneratedContent $agentsMdContent
    Remove-LegacyGlobalAgentsPath
    Write-Info "Global AGENTS.md: $GlobalAgentsPath"

    Write-Step 'Done'
    Write-Host 'Global installation prepared successfully.' -ForegroundColor Green
    Write-Host "Install root: $ResolvedInstallRoot"
    Write-Host "Global Pi settings: $GlobalPiAgentSettingsPath"
    Write-Host "Global AGENTS.md: $GlobalAgentsPath"
    Write-Host "Log file: $InstallLogPath"
    Write-Host ''
    Write-Host 'Start with:'
    Write-Host "  powershell -ExecutionPolicy Bypass -File `"$StartScriptPath`""
    Write-Host 'Or start pi from another repo/editor; the global Pi settings were updated as well.'

    Start-PiLoginIfNeeded -PiExecutablePath $piExe -WorkingDirectory $UserProfilePath -StartScriptPath $StartScriptPath
}
catch {
    $ScriptExitCode = 1
    Write-ErrorLine $_.Exception.Message
    if ($ResolvedInstallRoot) {
        Write-Host "Install root: $ResolvedInstallRoot" -ForegroundColor Yellow
    }
}
finally {
    if ($TranscriptStarted) {
        try { Stop-Transcript | Out-Null } catch {}
    }
}

exit $ScriptExitCode
