[CmdletBinding()]
param(
    [string]$ProjectRoot = (Get-Location).Path,
    [switch]$IncludeTwinCATAds,
    [string]$TwinCATAdsSource,
    [switch]$RequirePython,
    [switch]$UseLatestPackageVersions
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$IsWindowsPlatform = if (Get-Variable -Name 'IsWindows' -ErrorAction SilentlyContinue) {
    [bool]$IsWindows
}
else {
    ($PSVersionTable.PSEdition -eq 'Desktop') -or ([Environment]::OSVersion.Platform -eq [PlatformID]::Win32NT)
}

$InstallerScriptPath = if ($MyInvocation.MyCommand.Path) { $MyInvocation.MyCommand.Path } else { $PSCommandPath }
$ResolvedProjectRoot = (Resolve-Path -LiteralPath $ProjectRoot -ErrorAction Stop).Path
$ProjectScriptsDir = Join-Path $ResolvedProjectRoot 'scripts'
$PiDir = Join-Path $ResolvedProjectRoot '.pi'
$PackagesDir = Join-Path $ResolvedProjectRoot '.pi-packages'
$PackagesManifestPath = Join-Path $PackagesDir 'package.json'
$PackagesLockPath = Join-Path $PackagesDir 'package-lock.json'
$SettingsPath = Join-Path $PiDir 'settings.json'
$StartScriptPath = Join-Path $ProjectScriptsDir 'start-pi.ps1'
$SettingsBackupDir = Join-Path $PiDir 'backups'
$LogsDir = Join-Path $PiDir 'logs'
$InstallLogPath = Join-Path $LogsDir ("install-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.log')
$TranscriptStarted = $false
$ScriptExitCode = 0

$PinnedVersions = [ordered]@{
    'mempalace-pi'   = '0.2.0'
    'pi-lens'        = '3.8.26'
    'pi-mcp-adapter' = '2.4.0'
    'pi-subagents'   = '0.14.1'
    'pi-web-access'  = '0.10.6'
}

# Intentionally pinned: npm currently resolves the latest pi-coding-agent release
# to @mariozechner/pi-ai@^0.67.4, but that package version is not published.
$GlobalPiCodingAgentVersion = '0.67.3'

$PackageNames = @($PinnedVersions.Keys)

function Write-Step {
    param([Parameter(Mandatory = $true)][string]$Message)
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

function Write-Info {
    param([Parameter(Mandatory = $true)][string]$Message)
    Write-Host "[info] $Message" -ForegroundColor DarkGray
}

function Write-ErrorLine {
    param([Parameter(Mandatory = $true)][string]$Message)
    Write-Host "[error] $Message" -ForegroundColor Red
}

function Refresh-ProcessPath {
    $machinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    $combined = @($machinePath, $userPath) -join ';'
    if (-not [string]::IsNullOrWhiteSpace($combined)) {
        $env:Path = $combined
    }
}

function Ensure-Directory {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

function Set-GeneratedAgentsSection {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$GeneratedContent
    )

    $beginMarker = '<!-- BEGIN PI-SETUP-AUTOGENERATED -->'
    $endMarker = '<!-- END PI-SETUP-AUTOGENERATED -->'
    $block = $beginMarker + "`r`n" + $GeneratedContent.Trim() + "`r`n" + $endMarker + "`r`n"

    $existing = ''
    if (Test-Path -LiteralPath $Path) {
        $existing = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    }

    if ($existing -match [regex]::Escape($beginMarker) + '[\s\S]*?' + [regex]::Escape($endMarker)) {
        $updated = [regex]::Replace($existing, [regex]::Escape($beginMarker) + '[\s\S]*?' + [regex]::Escape($endMarker), $block.TrimEnd())
        Set-Content -LiteralPath $Path -Value ($updated.TrimEnd() + "`r`n") -Encoding UTF8
        return
    }

    $prefix = @"
# AGENTS.md

This file contains instructions for coding agents working in this repository.

"@

    if ([string]::IsNullOrWhiteSpace($existing)) {
        Set-Content -LiteralPath $Path -Value ($prefix + $block) -Encoding UTF8
    }
    else {
        $separator = if ($existing.EndsWith("`n")) { "" } else { "`r`n" }
        Set-Content -LiteralPath $Path -Value ($existing + $separator + "`r`n" + $block) -Encoding UTF8
    }
}

function Get-AgentsMdContent {
    param([switch]$IncludeTwinCATAds)

    $twincatSection = if ($IncludeTwinCATAds) {
@"
- `pi-twincat-ads`: Use for TwinCAT ADS communication and related automation tasks when the project requires it.
"@
    }
    else { '' }

    return @"
## Pi setup tools available in this workspace

Installed Pi packages:
- `pi-lens`: Prefer this for code understanding, LSP navigation, references, definitions, hover info, AST-aware search, and precise code changes.
- `mempalace-pi`: Treat this as a core part of the workflow. Use it actively for memory workflows, persistent project knowledge, reminders, decisions, follow-ups, and important discoveries that should survive the current session.
- `pi-subagents`: Use subagents when a task benefits from decomposition, parallel exploration, or specialized analysis.
- `pi-mcp-adapter`: Use MCP servers/tools when project tasks require external integrations or structured tool access.
- `pi-web-access`: Use web search/fetch only for external documentation or information not available in the repository.
$twincatSection
## Agent usage guidance

- Start with local repository context first: inspect files, settings, scripts, and code before using external tools.
- Use `mempalace-pi` as an active workflow component, not just as optional storage.
- When you learn something likely to matter later, store it in `mempalace-pi`.
- Before or during complex work, consider whether relevant prior knowledge from `mempalace-pi` may exist.
- Prefer `pi-lens`/LSP and AST-aware search over plain text search when navigating or modifying code.
- Use `pi-subagents` only when the task is complex enough to benefit from delegation.
- Use `pi-mcp-adapter` and `pi-web-access` deliberately, not by default.
- Keep edits minimal, precise, and consistent with the existing repository structure.
- When changing behavior, also update nearby documentation and scripts if needed.
- For Python-backed features such as `mempalace-pi` on Windows, prefer the provided start scripts and UTF-8 environment settings.

## Local project note

This `AGENTS.md` section was generated by `scripts/install-pi-stack.ps1`.
You may add project-specific instructions outside the autogenerated block.
"@
}

function Test-CommandExists {
    param([Parameter(Mandatory = $true)][string]$Name)
    return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Get-CommandPathSafe {
    param([Parameter(Mandatory = $true)][string]$Name)

    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }

    return $null
}

function Invoke-External {
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [string[]]$Arguments = @(),
        [string]$WorkingDirectory
    )

    if ($WorkingDirectory) {
        Push-Location $WorkingDirectory
    }

    try {
        Write-Info ("Run: " + $FilePath + ' ' + ($Arguments -join ' '))
        & $FilePath @Arguments
        $exitCode = $LASTEXITCODE
        if ($exitCode -ne 0) {
            throw "Command failed ($exitCode): $FilePath $($Arguments -join ' ')"
        }
    }
    finally {
        if ($WorkingDirectory) {
            Pop-Location
        }
    }
}

function Invoke-WithRetry {
    param(
        [Parameter(Mandatory = $true)][scriptblock]$Action,
        [Parameter(Mandatory = $true)][string]$Description,
        [int]$MaxAttempts = 3,
        [int]$DelaySeconds = 4
    )

    $attempt = 0
    while ($attempt -lt $MaxAttempts) {
        $attempt++
        try {
            Write-Info "$Description (attempt $attempt/$MaxAttempts)"
            & $Action
            return
        }
        catch {
            if ($attempt -ge $MaxAttempts) {
                throw
            }
            Write-Warning "$Description failed: $($_.Exception.Message)"
            Write-Info "Waiting $DelaySeconds seconds before the next attempt ..."
            Start-Sleep -Seconds $DelaySeconds
        }
    }
}

function Get-NpmViewText {
    param(
        [Parameter(Mandatory = $true)][string]$NpmExe,
        [Parameter(Mandatory = $true)][string[]]$Arguments
    )

    $output = & $NpmExe @Arguments 2>$null
    if ($LASTEXITCODE -ne 0) {
        return $null
    }

    $text = ($output | Out-String).Trim()
    if ([string]::IsNullOrWhiteSpace($text)) {
        return $null
    }

    return $text
}

function Get-NpmViewJson {
    param(
        [Parameter(Mandatory = $true)][string]$NpmExe,
        [Parameter(Mandatory = $true)][string[]]$Arguments
    )

    $text = Get-NpmViewText -NpmExe $NpmExe -Arguments $Arguments
    if ([string]::IsNullOrWhiteSpace($text)) {
        return $null
    }

    try {
        return ($text | ConvertFrom-Json)
    }
    catch {
        return $null
    }
}

function Test-NpmPackageVersionExists {
    param(
        [Parameter(Mandatory = $true)][string]$NpmExe,
        [Parameter(Mandatory = $true)][string]$PackageName,
        [Parameter(Mandatory = $true)][string]$Version
    )

    $result = & $NpmExe 'view' ("$PackageName@$Version") 'version' '--json' 2>$null
    if ($LASTEXITCODE -ne 0) {
        return $false
    }

    $text = ($result | Out-String).Trim().Trim('"')
    return $text -eq $Version
}

function Get-GlobalNpmRoot {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    $text = Get-NpmViewText -NpmExe $NpmExe -Arguments @('root', '-g')
    if ([string]::IsNullOrWhiteSpace($text)) {
        return $null
    }

    return $text.Split([Environment]::NewLine)[0].Trim()
}

function Get-GlobalPiCodingAgentPath {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    $globalRoot = Get-GlobalNpmRoot -NpmExe $NpmExe
    if ([string]::IsNullOrWhiteSpace($globalRoot)) {
        return $null
    }

    return (Join-Path $globalRoot '@mariozechner\pi-coding-agent')
}

function Get-PiRelatedRunningProcesses {
    $results = @()
    try {
        $processes = Get-CimInstance Win32_Process -ErrorAction Stop | Where-Object {
            $_.Name -match '^(node|npm|powershell|pwsh|cmd|bash)(\.exe)?$'
        }

        foreach ($process in $processes) {
            $commandLine = [string]$process.CommandLine
            if ($commandLine -match 'pi-coding-agent|\\npm\\pi\.cmd|\bpi\b|\bnpm\b') {
                $results += [PSCustomObject]@{
                    ProcessId   = $process.ProcessId
                    Name        = $process.Name
                    CommandLine = $commandLine
                }
            }
        }
    }
    catch {
        Write-Warning "Could not inspect running processes: $($_.Exception.Message)"
    }

    return @($results)
}

function Warn-AboutPiRelatedProcesses {
    $processes = @(Get-PiRelatedRunningProcesses)
    if ($processes.Count -eq 0) {
        return
    }

    Write-Warning 'Detected running pi/npm/node-related processes. On Windows these can lock files and cause npm EPERM cleanup/install issues.'
    foreach ($process in $processes | Select-Object -First 5) {
        Write-Warning ("PID {0} {1}: {2}" -f $process.ProcessId, $process.Name, $process.CommandLine)
    }
    if ($processes.Count -gt 5) {
        Write-Warning ("... and {0} more process(es)." -f ($processes.Count - 5))
    }
}

function Remove-StaleGlobalPiCodingAgent {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    $packagePath = Get-GlobalPiCodingAgentPath -NpmExe $NpmExe
    $appData = [Environment]::GetFolderPath('ApplicationData')
    $shimCandidates = @(
        (Join-Path $appData 'npm\pi.cmd'),
        (Join-Path $appData 'npm\pi'),
        (Join-Path $appData 'npm\node_modules\@mariozechner\pi-coding-agent')
    )

    Warn-AboutPiRelatedProcesses

    try {
        Invoke-External -FilePath $NpmExe -Arguments @('uninstall', '-g', '@mariozechner/pi-coding-agent', '--no-fund', '--no-audit')
    }
    catch {
        Write-Warning "Global uninstall cleanup failed: $($_.Exception.Message)"
    }

    foreach ($path in @($packagePath) + $shimCandidates) {
        if (-not $path) { continue }
        if (-not (Test-Path -LiteralPath $path)) { continue }
        try {
            Write-Info "Removing stale path: $path"
            Remove-Item -LiteralPath $path -Recurse -Force -ErrorAction Stop
        }
        catch {
            Write-Warning "Could not remove stale path '$path': $($_.Exception.Message)"
        }
    }
}

function Install-GlobalPiCodingAgent {
    param([Parameter(Mandatory = $true)][string]$NpmExe)

    Write-Step 'Installing or updating pi-coding-agent globally'

    if (-not (Test-NpmPackageVersionExists -NpmExe $NpmExe -PackageName '@mariozechner/pi-coding-agent' -Version $GlobalPiCodingAgentVersion)) {
        throw "Fallback package version is not available: @mariozechner/pi-coding-agent@$GlobalPiCodingAgentVersion"
    }

    $latestVersionText = Get-NpmViewText -NpmExe $NpmExe -Arguments @('view', '@mariozechner/pi-coding-agent', 'version', '--json')
    $latestVersion = if ($latestVersionText) { $latestVersionText.Trim('"') } else { $null }

    $latestPiAiRange = $null
    if ($latestVersion) {
        $latestDependenciesText = Get-NpmViewText -NpmExe $NpmExe -Arguments @('view', ("@mariozechner/pi-coding-agent@" + $latestVersion), 'dependencies', '--json')
        if ($latestDependenciesText -match '"@mariozechner/pi-ai"\s*:\s*"([^"]+)"') {
            $latestPiAiRange = $Matches[1]
        }
    }

    $fallbackNeeded = $false
    if ($latestPiAiRange -match '(\d+\.\d+\.\d+)') {
        $latestPiAiVersion = $Matches[1]
        if (-not (Test-NpmPackageVersionExists -NpmExe $NpmExe -PackageName '@mariozechner/pi-ai' -Version $latestPiAiVersion)) {
            Write-Warning "Latest @mariozechner/pi-coding-agent@$latestVersion depends on @mariozechner/pi-ai $latestPiAiRange, but that version is not published. Falling back to @mariozechner/pi-coding-agent@$GlobalPiCodingAgentVersion."
            $fallbackNeeded = $true
        }
    }
    elseif (-not $latestVersion) {
        Write-Warning "Could not reliably determine the latest @mariozechner/pi-coding-agent version from npm. Falling back to @mariozechner/pi-coding-agent@$GlobalPiCodingAgentVersion."
        $fallbackNeeded = $true
    }

    if (-not $fallbackNeeded) {
        try {
            Write-Info 'Trying latest @mariozechner/pi-coding-agent once before fallback validation.'
            Invoke-External -FilePath $NpmExe -Arguments @('install', '-g', '@mariozechner/pi-coding-agent', '--no-fund', '--no-audit')
            return
        }
        catch {
            Write-Warning "Installing latest @mariozechner/pi-coding-agent failed. Falling back to @mariozechner/pi-coding-agent@$GlobalPiCodingAgentVersion. Error: $($_.Exception.Message)"
        }
    }

    Write-Info 'Preparing a clean fallback install state for the global pi-coding-agent package.'
    Remove-StaleGlobalPiCodingAgent -NpmExe $NpmExe

    Invoke-WithRetry -Description "npm install -g @mariozechner/pi-coding-agent@$GlobalPiCodingAgentVersion" -Action {
        Invoke-External -FilePath $NpmExe -Arguments @('install', '-g', ("@mariozechner/pi-coding-agent@" + $GlobalPiCodingAgentVersion), '--no-fund', '--no-audit')
    } -MaxAttempts 3 -DelaySeconds 5
}

function Invoke-WingetInstall {
    param(
        [Parameter(Mandatory = $true)][string]$PackageId,
        [Parameter(Mandatory = $true)][string]$DisplayName
    )

    $winget = Get-CommandPathSafe -Name 'winget'
    if (-not $winget) {
        throw "'$DisplayName' is missing and winget is not available. Please install it manually."
    }

    Write-Step "Installing $DisplayName via winget"
    Invoke-WithRetry -Description "winget install $PackageId" -Action {
        Invoke-External -FilePath $winget -Arguments @(
            'install', '--id', $PackageId, '--exact', '--silent',
            '--accept-package-agreements', '--accept-source-agreements', '--disable-interactivity'
        )
    } -MaxAttempts 2 -DelaySeconds 5
    Refresh-ProcessPath
}

function Ensure-Command {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [string]$WingetPackageId,
        [string]$DisplayName = $Name,
        [switch]$Optional
    )

    if (Test-CommandExists -Name $Name) {
        return (Get-CommandPathSafe -Name $Name)
    }

    if ($WingetPackageId) {
        try {
            Invoke-WingetInstall -PackageId $WingetPackageId -DisplayName $DisplayName
        }
        catch {
            if ($Optional) {
                Write-Warning $_.Exception.Message
                return $null
            }
            throw
        }

        if (Test-CommandExists -Name $Name) {
            return (Get-CommandPathSafe -Name $Name)
        }
    }

    if ($Optional) {
        Write-Warning "'$DisplayName' was not found."
        return $null
    }

    throw "'$DisplayName' was not found."
}

function Get-NpmExecutable {
    $npmCmd = Get-CommandPathSafe -Name 'npm.cmd'
    if ($npmCmd) { return $npmCmd }

    $npm = Get-CommandPathSafe -Name 'npm'
    if ($npm) { return $npm }

    return $null
}

function Get-PiExecutable {
    $pi = Get-CommandPathSafe -Name 'pi'
    if ($pi) { return $pi }

    $appData = [Environment]::GetFolderPath('ApplicationData')
    $piCmd = Join-Path $appData 'npm\pi.cmd'
    if (Test-Path -LiteralPath $piCmd) {
        return $piCmd
    }

    return $null
}

function Load-JsonObject {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        return @{}
    }

    $raw = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    if ([string]::IsNullOrWhiteSpace($raw)) {
        return @{}
    }

    $obj = $raw | ConvertFrom-Json -AsHashtable
    if ($null -eq $obj) {
        return @{}
    }

    return $obj
}

function Save-JsonObject {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)]$Data
    )

    Ensure-Directory -Path (Split-Path -Parent $Path)
    $json = $Data | ConvertTo-Json -Depth 100
    Set-Content -LiteralPath $Path -Value ($json + "`n") -Encoding UTF8
}

function Backup-IfExists {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        return
    }

    Ensure-Directory -Path $SettingsBackupDir
    $timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
    $target = Join-Path $SettingsBackupDir ((Split-Path -Leaf $Path) + '.' + $timestamp + '.bak')
    Copy-Item -LiteralPath $Path -Destination $target -Force
    Write-Info "Backup created: $target"
}

function Merge-UniqueStrings {
    param(
        [object[]]$Existing,
        [object[]]$Incoming
    )

    $list = New-Object System.Collections.Generic.List[string]
    $seen = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

    foreach ($item in @($Existing) + @($Incoming)) {
        if ($null -eq $item) { continue }
        $text = [string]$item
        if ([string]::IsNullOrWhiteSpace($text)) { continue }
        if ($seen.Add($text)) {
            $list.Add($text)
        }
    }

    return @($list)
}

function Get-DependencyMap {
    $dependencies = [ordered]@{}
    foreach ($name in $PackageNames) {
        if ($UseLatestPackageVersions) {
            $dependencies[$name] = 'latest'
        }
        else {
            $dependencies[$name] = $PinnedVersions[$name]
        }
    }
    return $dependencies
}

function Ensure-PackageManifest {
    $manifest = [ordered]@{
        name        = 'pi-setup-stack'
        private     = $true
        description = 'Local Pi stack for this project'
        dependencies = (Get-DependencyMap)
    }

    if (-not (Test-Path -LiteralPath $PackagesManifestPath)) {
        Write-Info "Creating $PackagesManifestPath"
        Save-JsonObject -Path $PackagesManifestPath -Data $manifest
        return
    }

    $existing = Load-JsonObject -Path $PackagesManifestPath
    if (-not $existing.ContainsKey('name')) { $existing['name'] = $manifest['name'] }
    $existing['private'] = $true
    if (-not $existing.ContainsKey('description')) { $existing['description'] = $manifest['description'] }

    $deps = [ordered]@{}
    if ($existing.ContainsKey('dependencies') -and $existing['dependencies']) {
        foreach ($entry in $existing['dependencies'].GetEnumerator()) {
            $deps[$entry.Key] = $entry.Value
        }
    }

    foreach ($entry in (Get-DependencyMap).GetEnumerator()) {
        $deps[$entry.Key] = $entry.Value
    }

    $existing['dependencies'] = $deps
    Save-JsonObject -Path $PackagesManifestPath -Data $existing
}

function Get-GitBashPath {
    $candidates = @(
        'C:\Program Files\Git\bin\bash.exe',
        'C:\Program Files (x86)\Git\bin\bash.exe'
    )

    foreach ($candidate in $candidates) {
        if (Test-Path -LiteralPath $candidate) {
            return $candidate
        }
    }

    $bash = Get-CommandPathSafe -Name 'bash'
    if ($bash) { return $bash }
    return $null
}

function Test-PackageInstalled {
    param([Parameter(Mandatory = $true)][string]$PackageName)

    $packagePath = Join-Path $PackagesDir ("node_modules\\$PackageName")
    return (Test-Path -LiteralPath $packagePath)
}

function Assert-PackageInstalled {
    param([Parameter(Mandatory = $true)][string]$PackageName)

    if (-not (Test-PackageInstalled -PackageName $PackageName)) {
        throw "Package missing after npm install: $PackageName"
    }
}

Ensure-Directory -Path $PiDir
Ensure-Directory -Path $LogsDir

try {
    try {
        Start-Transcript -Path $InstallLogPath -Force | Out-Null
        $TranscriptStarted = $true
    }
    catch {
        Write-Warning "Could not start transcript: $($_.Exception.Message)"
    }

    Write-Info "Install log: $InstallLogPath"
    Write-Step 'Checking and installing prerequisites'

    if (-not $IsWindowsPlatform) {
        throw 'This bootstrap script is intended for Windows.'
    }

    $nodePath = Ensure-Command -Name 'node' -WingetPackageId 'OpenJS.NodeJS.LTS' -DisplayName 'Node.js LTS'
    $npmPath = Ensure-Command -Name 'npm' -WingetPackageId 'OpenJS.NodeJS.LTS' -DisplayName 'npm'
    $npmExe = Get-NpmExecutable
    if (-not $npmExe) {
        throw 'Could not resolve npm.'
    }

    Write-Host "node: $(& $nodePath --version)"
    Write-Host "npm:  $(& $npmExe --version)"

    $gitBashPath = Get-GitBashPath
    if (-not $gitBashPath) {
        Ensure-Command -Name 'git' -WingetPackageId 'Git.Git' -DisplayName 'Git for Windows'
        $gitBashPath = Get-GitBashPath
    }

    if ($gitBashPath) {
        Write-Host "bash: $gitBashPath"
    } else {
        throw 'No bash shell found. Pi needs Git Bash or another bash.exe on Windows.'
    }

    $pythonPath = Get-CommandPathSafe -Name 'py'
    if (-not $pythonPath) {
        $pythonPath = Get-CommandPathSafe -Name 'python'
    }

    if (-not $pythonPath) {
        $pythonPath = Ensure-Command -Name 'py' -WingetPackageId 'Python.Python.3.12' -DisplayName 'Python 3' -Optional:(-not $RequirePython)
        if (-not $pythonPath) {
            $pythonPath = Get-CommandPathSafe -Name 'python'
        }
    }

    if ($RequirePython -and -not $pythonPath) {
        throw 'Python is required but could not be installed or found.'
    }

    if ($pythonPath) {
        try {
            Write-Host "python: $(& $pythonPath --version 2>&1)"
        }
        catch {
            Write-Warning "Python was found, but its version could not be read: $($_.Exception.Message)"
        }
    } else {
        Write-Warning 'Python was not found. mempalace-pi may require a manual Python installation later.'
    }

    Install-GlobalPiCodingAgent -NpmExe $npmExe
    Refresh-ProcessPath

    $piExe = Get-PiExecutable
    if (-not $piExe) {
        throw 'pi was not found after the global npm install.'
    }

    Write-Host "pi:   $(& $piExe --version)"

    Write-Step 'Preparing project structure'
    Ensure-Directory -Path $ProjectScriptsDir
    Ensure-Directory -Path $PackagesDir
    Ensure-PackageManifest

    Write-Step 'Installing local Pi packages via npm'
    Invoke-WithRetry -Description 'npm install for .pi-packages' -Action {
        Invoke-External -FilePath $npmExe -WorkingDirectory $PackagesDir -Arguments @('install', '--no-fund', '--no-audit')
    } -MaxAttempts 3 -DelaySeconds 5

    foreach ($packageName in $PackageNames) {
        Assert-PackageInstalled -PackageName $packageName
    }

    if ($IncludeTwinCATAds) {
        if ([string]::IsNullOrWhiteSpace($TwinCATAdsSource)) {
            throw 'If -IncludeTwinCATAds is set, -TwinCATAdsSource must also be provided.'
        }

        $resolvedTwinCATAds = (Resolve-Path -LiteralPath $TwinCATAdsSource -ErrorAction Stop).Path
        Write-Step 'Installing pi-twincat-ads from local path'
        Invoke-WithRetry -Description 'npm install pi-twincat-ads' -Action {
            Invoke-External -FilePath $npmExe -WorkingDirectory $PackagesDir -Arguments @('install', $resolvedTwinCATAds, '--no-fund', '--no-audit')
        } -MaxAttempts 3 -DelaySeconds 5
        Assert-PackageInstalled -PackageName 'pi-twincat-ads'
    }

    Write-Step 'Writing robust Pi project configuration'
    Backup-IfExists -Path $SettingsPath
    $settings = Load-JsonObject -Path $SettingsPath

    $settings['npmCommand'] = @($npmExe)
    $settings['shellPath'] = $gitBashPath
    $settings['sessionDir'] = '.pi/sessions'

    $packagePaths = @(
        '../.pi-packages/node_modules/pi-subagents',
        '../.pi-packages/node_modules/pi-mcp-adapter',
        '../.pi-packages/node_modules/pi-lens',
        '../.pi-packages/node_modules/pi-web-access',
        '../.pi-packages/node_modules/mempalace-pi'
    )

    if ($IncludeTwinCATAds) {
        $packagePaths += '../.pi-packages/node_modules/pi-twincat-ads'
    }

    $settings['packages'] = Merge-UniqueStrings -Existing $settings['packages'] -Incoming $packagePaths
    Save-JsonObject -Path $SettingsPath -Data $settings

    Write-Step 'Writing start script for mempalace/Python UTF-8'
    $startScript = @"
param(
    [Parameter(ValueFromRemainingArguments = `$true)]
    [string[]]`$PiArgs
)

`$ErrorActionPreference = 'Stop'
`$env:PYTHONUTF8 = '1'
`$env:PYTHONIOENCODING = 'utf-8'

`$ScriptDir = Split-Path -Parent `$MyInvocation.MyCommand.Path
`$ProjectRoot = Split-Path -Parent `$ScriptDir
Set-Location `$ProjectRoot

`$piCmd = Get-Command 'pi' -ErrorAction SilentlyContinue
`$piCmdPath = if (`$piCmd) { `$piCmd.Source } else { `$null }
if (-not `$piCmdPath) {
    `$piFallback = Join-Path ([Environment]::GetFolderPath('ApplicationData')) 'npm\pi.cmd'
    if (Test-Path -LiteralPath `$piFallback) {
        `$piCmdPath = `$piFallback
    }
}

if (-not `$piCmdPath) {
    throw 'pi was not found. Please run scripts/install-pi-stack.ps1 first.'
}

& `$piCmdPath @PiArgs
exit `$LASTEXITCODE
"@
    Set-Content -LiteralPath $StartScriptPath -Value $startScript -Encoding UTF8

    Write-Step 'Validating local package paths'
    foreach ($packagePath in $packagePaths) {
        $resolvedPath = Resolve-Path -LiteralPath (Join-Path $PiDir $packagePath) -ErrorAction Stop
        Write-Info "OK: $resolvedPath"
    }

    Write-Step 'Writing AGENTS.md'
    $agentsMdPath = Join-Path $ResolvedProjectRoot 'AGENTS.md'
    $agentsMdContent = Get-AgentsMdContent -IncludeTwinCATAds:$IncludeTwinCATAds
    Set-GeneratedAgentsSection -Path $agentsMdPath -GeneratedContent $agentsMdContent
    Write-Info "AGENTS.md: $agentsMdPath"

    Write-Step 'Done'
    Write-Host 'Successfully prepared:' -ForegroundColor Green
    Write-Host "  - Project root: $ResolvedProjectRoot"
    Write-Host "  - Global: @mariozechner/pi-coding-agent"
    foreach ($packageName in $PackageNames) {
        Write-Host "  - Local:  $packageName"
    }
    if ($IncludeTwinCATAds) {
        Write-Host '  - Local:  pi-twincat-ads'
    }

    Write-Host "`nImportant files:"
    Write-Host "  - $PackagesManifestPath"
    if (Test-Path -LiteralPath $PackagesLockPath) {
        Write-Host "  - $PackagesLockPath"
    }
    Write-Host "  - $SettingsPath"
    Write-Host "  - $StartScriptPath"
    Write-Host "  - $agentsMdPath"
    Write-Host "  - $InstallerScriptPath"
    Write-Host "  - $InstallLogPath"

    Write-Host "`nRecommended startup on Windows from the target repo:"
    Write-Host "  powershell -ExecutionPolicy Bypass -File .\scripts\start-pi.ps1"
    Write-Host "  # target repo: $ResolvedProjectRoot"
}
catch {
    $ScriptExitCode = 1
    Write-ErrorLine $_.Exception.Message
    Write-Host "Log file: $InstallLogPath" -ForegroundColor Yellow
}
finally {
    if ($TranscriptStarted) {
        try {
            Stop-Transcript | Out-Null
        }
        catch {
        }
    }
}

exit $ScriptExitCode
